var _permanent_dash_worm_ability_8cs =
[
    [ "RogueGenesia.Actors.Survival.BossAbility.Worm.PermanentDashWormAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_worm_1_1_permanent_dash_worm_ability.html", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_worm_1_1_permanent_dash_worm_ability" ]
];