var _s_s_u_anachronistic_charge_duration_info_class_8cs =
[
    [ "RogueGenesia.Data.SSUAnachronisticChargeDurationInfoClass", "class_rogue_genesia_1_1_data_1_1_s_s_u_anachronistic_charge_duration_info_class.html", "class_rogue_genesia_1_1_data_1_1_s_s_u_anachronistic_charge_duration_info_class" ]
];