var _s_s_u_monster_knowledge_received_damage_info_class_8cs =
[
    [ "RogueGenesia.Data.SSUMonsterKnowledgeReceivedDamageInfoClass", "class_rogue_genesia_1_1_data_1_1_s_s_u_monster_knowledge_received_damage_info_class.html", "class_rogue_genesia_1_1_data_1_1_s_s_u_monster_knowledge_received_damage_info_class" ]
];