var _shaman_magic_bullet_storm_8cs =
[
    [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.ShamanMagicBulletStorm", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_magic_bullet_storm.html", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_magic_bullet_storm" ]
];