var _shaman_magic_bullet_storm_ability_8cs =
[
    [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.ShamanMagicBulletStormAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_magic_bullet_storm_ability.html", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_magic_bullet_storm_ability" ]
];