var _shop_buyable_card_selection_over_cap_info_class_8cs =
[
    [ "RogueGenesia.Data.ShopBuyableCardSelectionOverCapInfoClass", "class_rogue_genesia_1_1_data_1_1_shop_buyable_card_selection_over_cap_info_class.html", "class_rogue_genesia_1_1_data_1_1_shop_buyable_card_selection_over_cap_info_class" ]
];