var _vampire_queen___dash_slash_ability_8cs =
[
    [ "RogueGenesia.Actors.Survival.BossAbility.Worm.VampireQueen_DashSlashAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_worm_1_1_vampire_queen___dash_slash_ability.html", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_worm_1_1_vampire_queen___dash_slash_ability" ]
];