var _vampire_queen___dio_knife_8cs =
[
    [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.VampireQueen_DioKnife", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_vampire_queen___dio_knife.html", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_vampire_queen___dio_knife" ]
];