var _vampire_queen___laser___phase2_end_8cs =
[
    [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.VampireQueen_Laser_Phase2End", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_vampire_queen___laser___phase2_end.html", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_vampire_queen___laser___phase2_end" ]
];