var annotated_dup =
[
    [ "ModGenesia", "namespace_mod_genesia.html", [
      [ "AchievementAPI", "class_mod_genesia_1_1_achievement_a_p_i.html", "class_mod_genesia_1_1_achievement_a_p_i" ],
      [ "AvatarAPI", "class_mod_genesia_1_1_avatar_a_p_i.html", "class_mod_genesia_1_1_avatar_a_p_i" ],
      [ "BuffAPI", "class_mod_genesia_1_1_buff_a_p_i.html", "class_mod_genesia_1_1_buff_a_p_i" ],
      [ "ModCardRequirement", "class_mod_genesia_1_1_mod_card_requirement.html", "class_mod_genesia_1_1_mod_card_requirement" ],
      [ "StatsModifierJSonReaser", "struct_mod_genesia_1_1_stats_modifier_j_son_reaser.html", "struct_mod_genesia_1_1_stats_modifier_j_son_reaser" ],
      [ "SoulCardJsonReader", "struct_mod_genesia_1_1_soul_card_json_reader.html", "struct_mod_genesia_1_1_soul_card_json_reader" ],
      [ "CardStatsRequirements", "struct_mod_genesia_1_1_card_stats_requirements.html", "struct_mod_genesia_1_1_card_stats_requirements" ],
      [ "CardRequirements", "struct_mod_genesia_1_1_card_requirements.html", "struct_mod_genesia_1_1_card_requirements" ],
      [ "SCSORequirementJsonReader", "struct_mod_genesia_1_1_s_c_s_o_requirement_json_reader.html", "struct_mod_genesia_1_1_s_c_s_o_requirement_json_reader" ],
      [ "SoulCardCreationData", "class_mod_genesia_1_1_soul_card_creation_data.html", "class_mod_genesia_1_1_soul_card_creation_data" ],
      [ "CardAPI", "class_mod_genesia_1_1_card_a_p_i.html", "class_mod_genesia_1_1_card_a_p_i" ],
      [ "ChallengeAPI", "class_mod_genesia_1_1_challenge_a_p_i.html", "class_mod_genesia_1_1_challenge_a_p_i" ],
      [ "ContentAPI", "class_mod_genesia_1_1_content_a_p_i.html", "class_mod_genesia_1_1_content_a_p_i" ],
      [ "EquipmentAPI", "class_mod_genesia_1_1_equipment_a_p_i.html", "class_mod_genesia_1_1_equipment_a_p_i" ],
      [ "ModCreationUtils", "class_mod_genesia_1_1_mod_creation_utils.html", "class_mod_genesia_1_1_mod_creation_utils" ],
      [ "ModInfo", "class_mod_genesia_1_1_mod_info.html", "class_mod_genesia_1_1_mod_info" ],
      [ "ModVersion", "class_mod_genesia_1_1_mod_version.html", "class_mod_genesia_1_1_mod_version" ],
      [ "ModData", "class_mod_genesia_1_1_mod_data.html", "class_mod_genesia_1_1_mod_data" ],
      [ "ModGenesia", "class_mod_genesia_1_1_mod_genesia.html", "class_mod_genesia_1_1_mod_genesia" ],
      [ "RogueGenesiaMod", "class_mod_genesia_1_1_rogue_genesia_mod.html", "class_mod_genesia_1_1_rogue_genesia_mod" ],
      [ "ModLoader", "class_mod_genesia_1_1_mod_loader.html", "class_mod_genesia_1_1_mod_loader" ],
      [ "AssemblyLoader", "class_mod_genesia_1_1_assembly_loader.html", "class_mod_genesia_1_1_assembly_loader" ],
      [ "ModOption", "class_mod_genesia_1_1_mod_option.html", "class_mod_genesia_1_1_mod_option" ],
      [ "PetAPI", "class_mod_genesia_1_1_pet_a_p_i.html", "class_mod_genesia_1_1_pet_a_p_i" ],
      [ "StageCreationInfo", "class_mod_genesia_1_1_stage_creation_info.html", "class_mod_genesia_1_1_stage_creation_info" ],
      [ "StageAPI", "class_mod_genesia_1_1_stage_a_p_i.html", "class_mod_genesia_1_1_stage_a_p_i" ],
      [ "ManifestBuilder", "class_mod_genesia_1_1_manifest_builder.html", "class_mod_genesia_1_1_manifest_builder" ],
      [ "ModListManager", "class_mod_genesia_1_1_mod_list_manager.html", "class_mod_genesia_1_1_mod_list_manager" ],
      [ "WorkShopInformation", "class_mod_genesia_1_1_work_shop_information.html", "class_mod_genesia_1_1_work_shop_information" ],
      [ "SteamWorkShop", "class_mod_genesia_1_1_steam_work_shop.html", "class_mod_genesia_1_1_steam_work_shop" ]
    ] ],
    [ "ModButton", "class_mod_button.html", "class_mod_button" ]
];