var dir_5b95e7a840fc90fa76f5ccdfa96a1783 =
[
    [ "AchievementMenu.cs", "_achievement_menu_8cs.html", "_achievement_menu_8cs" ],
    [ "ArtifactList.cs", "_artifact_list_8cs.html", "_artifact_list_8cs" ],
    [ "ArtifactListPanel.cs", "_artifact_list_panel_8cs.html", "_artifact_list_panel_8cs" ],
    [ "CollectibleListPanel.cs", "_collectible_list_panel_8cs.html", "_collectible_list_panel_8cs" ],
    [ "CollectibleListUI.cs", "_collectible_list_u_i_8cs.html", "_collectible_list_u_i_8cs" ],
    [ "EmptyModifier_Forge.cs", "_empty_modifier___forge_8cs.html", "_empty_modifier___forge_8cs" ],
    [ "Equipment_Tooltip_Modifier.cs", "_equipment___tooltip___modifier_8cs.html", "_equipment___tooltip___modifier_8cs" ],
    [ "EquipmentModifier_CreationUI.cs", "_equipment_modifier___creation_u_i_8cs.html", "_equipment_modifier___creation_u_i_8cs" ],
    [ "EquipmentModifier_EncyclopediaUI.cs", "_equipment_modifier___encyclopedia_u_i_8cs.html", "_equipment_modifier___encyclopedia_u_i_8cs" ],
    [ "EquipmentModifierList.cs", "_equipment_modifier_list_8cs.html", "_equipment_modifier_list_8cs" ],
    [ "GameHistoryDetails.cs", "_game_history_details_8cs.html", "_game_history_details_8cs" ],
    [ "GameHistoryPannel.cs", "_game_history_pannel_8cs.html", "_game_history_pannel_8cs" ],
    [ "GameHistoryTab.cs", "_game_history_tab_8cs.html", "_game_history_tab_8cs" ],
    [ "GeneralStats.cs", "_general_stats_8cs.html", "_general_stats_8cs" ],
    [ "ListPanel.cs", "_list_panel_8cs.html", "_list_panel_8cs" ],
    [ "MainModifier_Forge.cs", "_main_modifier___forge_8cs.html", "_main_modifier___forge_8cs" ],
    [ "ModifierCrafting.cs", "_modifier_crafting_8cs.html", "_modifier_crafting_8cs" ],
    [ "ModifierDataMenu.cs", "_modifier_data_menu_8cs.html", "_modifier_data_menu_8cs" ],
    [ "ModifierMenu_New.cs", "_modifier_menu___new_8cs.html", "_modifier_menu___new_8cs" ],
    [ "ModifierTooltip.cs", "_modifier_tooltip_8cs.html", "_modifier_tooltip_8cs" ],
    [ "MonsterAbilitiesListPanel.cs", "_monster_abilities_list_panel_8cs.html", "_monster_abilities_list_panel_8cs" ],
    [ "MonsterAbilitiesListUI.cs", "_monster_abilities_list_u_i_8cs.html", "_monster_abilities_list_u_i_8cs" ],
    [ "MonsterListPanel.cs", "_monster_list_panel_8cs.html", "_monster_list_panel_8cs" ],
    [ "MonsterListUI.cs", "_monster_list_u_i_8cs.html", "_monster_list_u_i_8cs" ],
    [ "SecondaryModifier_Forge.cs", "_secondary_modifier___forge_8cs.html", "_secondary_modifier___forge_8cs" ],
    [ "StatsMenu.cs", "_stats_menu_8cs.html", "_stats_menu_8cs" ]
];