var dir_49237041992ffb5334c2eb02fae8555f =
[
    [ "AdventurerLicenceArtifact.cs", "_adventurer_licence_artifact_8cs.html", "_adventurer_licence_artifact_8cs" ],
    [ "BattleRubyArtifact.cs", "_battle_ruby_artifact_8cs.html", "_battle_ruby_artifact_8cs" ],
    [ "BeefStatueArtifact.cs", "_beef_statue_artifact_8cs.html", "_beef_statue_artifact_8cs" ],
    [ "BhikkhuPearlArtifact.cs", "_bhikkhu_pearl_artifact_8cs.html", "_bhikkhu_pearl_artifact_8cs" ],
    [ "BrokenStatuetteArtifact.cs", "_broken_statuette_artifact_8cs.html", "_broken_statuette_artifact_8cs" ],
    [ "ChampionBracerArtifact.cs", "_champion_bracer_artifact_8cs.html", "_champion_bracer_artifact_8cs" ],
    [ "CheatingHandArtifact.cs", "_cheating_hand_artifact_8cs.html", "_cheating_hand_artifact_8cs" ],
    [ "ChickenStatueArtifact.cs", "_chicken_statue_artifact_8cs.html", "_chicken_statue_artifact_8cs" ],
    [ "CollectionBookArtifact.cs", "_collection_book_artifact_8cs.html", "_collection_book_artifact_8cs" ],
    [ "CowardSaphirArtifact.cs", "_coward_saphir_artifact_8cs.html", "_coward_saphir_artifact_8cs" ],
    [ "CursedBeltArtifact.cs", "_cursed_belt_artifact_8cs.html", "_cursed_belt_artifact_8cs" ],
    [ "DiceArtifact.cs", "_dice_artifact_8cs.html", "_dice_artifact_8cs" ],
    [ "GlassSwordArtifact.cs", "_glass_sword_artifact_8cs.html", "_glass_sword_artifact_8cs" ],
    [ "HermesHoodArtifact.cs", "_hermes_hood_artifact_8cs.html", "_hermes_hood_artifact_8cs" ],
    [ "HolyCrossArtifact.cs", "_holy_cross_artifact_8cs.html", "_holy_cross_artifact_8cs" ],
    [ "LightningBootsArtifact.cs", "_lightning_boots_artifact_8cs.html", "_lightning_boots_artifact_8cs" ],
    [ "MagnifyingGlassArtifact.cs", "_magnifying_glass_artifact_8cs.html", "_magnifying_glass_artifact_8cs" ],
    [ "MartyrCloakArtifact.cs", "_martyr_cloak_artifact_8cs.html", "_martyr_cloak_artifact_8cs" ],
    [ "MidasSwordArtifact.cs", "_midas_sword_artifact_8cs.html", "_midas_sword_artifact_8cs" ],
    [ "OldCoinArtifact.cs", "_old_coin_artifact_8cs.html", "_old_coin_artifact_8cs" ],
    [ "OuroborosNecklaceArtifact.cs", "_ouroboros_necklace_artifact_8cs.html", "_ouroboros_necklace_artifact_8cs" ],
    [ "PhoenixTotemArtifact.cs", "_phoenix_totem_artifact_8cs.html", "_phoenix_totem_artifact_8cs" ],
    [ "PorkStatueArtifact.cs", "_pork_statue_artifact_8cs.html", "_pork_statue_artifact_8cs" ],
    [ "SacredSwordArtifact.cs", "_sacred_sword_artifact_8cs.html", "_sacred_sword_artifact_8cs" ],
    [ "SageLeafArtifact.cs", "_sage_leaf_artifact_8cs.html", "_sage_leaf_artifact_8cs" ],
    [ "SaintShinboneArtifact.cs", "_saint_shinbone_artifact_8cs.html", "_saint_shinbone_artifact_8cs" ],
    [ "SheepStatueArtifact.cs", "_sheep_statue_artifact_8cs.html", "_sheep_statue_artifact_8cs" ],
    [ "ShopKeeperPlateArtifact.cs", "_shop_keeper_plate_artifact_8cs.html", "_shop_keeper_plate_artifact_8cs" ],
    [ "SoulGauntletArtifact.cs", "_soul_gauntlet_artifact_8cs.html", "_soul_gauntlet_artifact_8cs" ],
    [ "TrainingWeightArtifact.cs", "_training_weight_artifact_8cs.html", "_training_weight_artifact_8cs" ],
    [ "TrollBloodArtifact.cs", "_troll_blood_artifact_8cs.html", "_troll_blood_artifact_8cs" ],
    [ "VoidStatueArtifact.cs", "_void_statue_artifact_8cs.html", "_void_statue_artifact_8cs" ],
    [ "WindLaceArtifact.cs", "_wind_lace_artifact_8cs.html", "_wind_lace_artifact_8cs" ]
];