var hierarchy =
[
    [ "ModGenesia.AchievementAPI", "class_mod_genesia_1_1_achievement_a_p_i.html", null ],
    [ "ModGenesia.AssemblyLoader", "class_mod_genesia_1_1_assembly_loader.html", null ],
    [ "ModGenesia.ModLoader.AssemblyPair", "class_mod_genesia_1_1_mod_loader_1_1_assembly_pair.html", null ],
    [ "ModGenesia.AvatarAPI", "class_mod_genesia_1_1_avatar_a_p_i.html", null ],
    [ "ModGenesia.BuffAPI", "class_mod_genesia_1_1_buff_a_p_i.html", null ],
    [ "ModGenesia.CardAPI", "class_mod_genesia_1_1_card_a_p_i.html", null ],
    [ "ModGenesia.CardRequirements", "struct_mod_genesia_1_1_card_requirements.html", null ],
    [ "ModGenesia.CardStatsRequirements", "struct_mod_genesia_1_1_card_stats_requirements.html", null ],
    [ "ModGenesia.ChallengeAPI", "class_mod_genesia_1_1_challenge_a_p_i.html", null ],
    [ "ModGenesia.ContentAPI", "class_mod_genesia_1_1_content_a_p_i.html", null ],
    [ "ModGenesia.EquipmentAPI", "class_mod_genesia_1_1_equipment_a_p_i.html", null ],
    [ "ModGenesia.ModCardRequirement", "class_mod_genesia_1_1_mod_card_requirement.html", null ],
    [ "ModGenesia.ModCreationUtils", "class_mod_genesia_1_1_mod_creation_utils.html", null ],
    [ "ModGenesia.ModData", "class_mod_genesia_1_1_mod_data.html", null ],
    [ "ModGenesia.ModOption.ModdedBindingData", "struct_mod_genesia_1_1_mod_option_1_1_modded_binding_data.html", null ],
    [ "ModGenesia.ModGenesia", "class_mod_genesia_1_1_mod_genesia.html", null ],
    [ "ModGenesia.ModInfo", "class_mod_genesia_1_1_mod_info.html", null ],
    [ "ModGenesia.SteamWorkShop.ModInstallInfo", "class_mod_genesia_1_1_steam_work_shop_1_1_mod_install_info.html", null ],
    [ "ModGenesia.ModLoader", "class_mod_genesia_1_1_mod_loader.html", null ],
    [ "ModGenesia.ModOption", "class_mod_genesia_1_1_mod_option.html", null ],
    [ "ModGenesia.ModVersion", "class_mod_genesia_1_1_mod_version.html", null ],
    [ "MonoBehaviour", null, [
      [ "ModButton", "class_mod_button.html", null ],
      [ "ModGenesia.ManifestBuilder", "class_mod_genesia_1_1_manifest_builder.html", null ],
      [ "ModGenesia.ModListManager", "class_mod_genesia_1_1_mod_list_manager.html", null ]
    ] ],
    [ "ModGenesia.PetAPI", "class_mod_genesia_1_1_pet_a_p_i.html", null ],
    [ "ModGenesia.RogueGenesiaMod", "class_mod_genesia_1_1_rogue_genesia_mod.html", null ],
    [ "ModGenesia.SCSORequirementJsonReader", "struct_mod_genesia_1_1_s_c_s_o_requirement_json_reader.html", null ],
    [ "ModGenesia.SoulCardCreationData", "class_mod_genesia_1_1_soul_card_creation_data.html", null ],
    [ "ModGenesia.SoulCardJsonReader", "struct_mod_genesia_1_1_soul_card_json_reader.html", null ],
    [ "ModGenesia.StageAPI", "class_mod_genesia_1_1_stage_a_p_i.html", null ],
    [ "ModGenesia.StageCreationInfo", "class_mod_genesia_1_1_stage_creation_info.html", null ],
    [ "ModGenesia.StatsModifierJSonReaser", "struct_mod_genesia_1_1_stats_modifier_j_son_reaser.html", null ],
    [ "ModGenesia.SteamWorkShop", "class_mod_genesia_1_1_steam_work_shop.html", null ],
    [ "ModGenesia.SteamWorkShop.WorkshopDownloadProgress", "class_mod_genesia_1_1_steam_work_shop_1_1_workshop_download_progress.html", null ],
    [ "ModGenesia.WorkShopInformation", "class_mod_genesia_1_1_work_shop_information.html", null ]
];