var hierarchy =
[
    [ "ModGenesia.AchievementAPI", "class_mod_genesia_1_1_achievement_a_p_i.html", null ],
    [ "RogueGenesia.AchievementSave", "struct_rogue_genesia_1_1_achievement_save.html", null ],
    [ "RogueGenesia.AchievementSaveData", "class_rogue_genesia_1_1_achievement_save_data.html", null ],
    [ "RogueGenesia.Data.ActiveTalentLevelData", "class_rogue_genesia_1_1_data_1_1_active_talent_level_data.html", null ],
    [ "RogueGenesia.Data.ArtifactData", "struct_rogue_genesia_1_1_data_1_1_artifact_data.html", null ],
    [ "RogueGenesia.Save.ArtifactSave", "class_rogue_genesia_1_1_save_1_1_artifact_save.html", null ],
    [ "ModGenesia.AssemblyLoader", "class_mod_genesia_1_1_assembly_loader.html", null ],
    [ "ModGenesia.ModLoader.AssemblyPair", "class_mod_genesia_1_1_mod_loader_1_1_assembly_pair.html", null ],
    [ "RogueGenesia.Data.AttackInformation", "struct_rogue_genesia_1_1_data_1_1_attack_information.html", null ],
    [ "RogueGenesia.Data.AvatarAnimations", "class_rogue_genesia_1_1_data_1_1_avatar_animations.html", null ],
    [ "ModGenesia.AvatarAPI", "class_mod_genesia_1_1_avatar_a_p_i.html", null ],
    [ "RogueGenesia.Data.AvatarContainer", "class_rogue_genesia_1_1_data_1_1_avatar_container.html", null ],
    [ "RogueGenesia.Data.AvatarData", "class_rogue_genesia_1_1_data_1_1_avatar_data.html", [
      [ "RogueGenesia.Data.CorruptedRog", "class_rogue_genesia_1_1_data_1_1_corrupted_rog.html", null ],
      [ "RogueGenesia.Data.DemonMerchantData", "class_rogue_genesia_1_1_data_1_1_demon_merchant_data.html", null ],
      [ "RogueGenesia.Data.DogRogData", "class_rogue_genesia_1_1_data_1_1_dog_rog_data.html", null ],
      [ "RogueGenesia.Data.GunSlingerData", "class_rogue_genesia_1_1_data_1_1_gun_slinger_data.html", null ],
      [ "RogueGenesia.Data.RogData", "class_rogue_genesia_1_1_data_1_1_rog_data.html", null ],
      [ "RogueGenesia.Data.RogueData", "class_rogue_genesia_1_1_data_1_1_rogue_data.html", null ]
    ] ],
    [ "RogueGenesia.Data.AvatarSave", "class_rogue_genesia_1_1_data_1_1_avatar_save.html", null ],
    [ "RogueGenesia.Actors.Survival.Buff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_buff.html", [
      [ "RogueGenesia.Actors.Survival.AttackSpeedFromDashBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_attack_speed_from_dash_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.BenedictionBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_benediction_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.BerserkBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_berserk_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.DamageOnReloadBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_damage_on_reload_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.DesynchronisedHeartBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_desynchronised_heart_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.EnvyBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_envy_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.GluttonyBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_gluttony_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.GreedStacks", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_greed_stacks.html", null ],
      [ "RogueGenesia.Actors.Survival.HealthBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_health_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.ImmovableActive", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_immovable_active.html", null ],
      [ "RogueGenesia.Actors.Survival.ImmovableCD", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_immovable_c_d.html", null ],
      [ "RogueGenesia.Actors.Survival.JaaldBlessing", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_jaald_blessing.html", null ],
      [ "RogueGenesia.Actors.Survival.LunaBlessing", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_luna_blessing.html", null ],
      [ "RogueGenesia.Actors.Survival.LustBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_lust_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.MartyrBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_martyr_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.MartyrCloakCD", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_martyr_cloak_c_d.html", null ],
      [ "RogueGenesia.Actors.Survival.MartyrCloakEffect", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_martyr_cloak_effect.html", null ],
      [ "RogueGenesia.Actors.Survival.MultiTaskingCD5", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_multi_tasking_c_d5.html", null ],
      [ "RogueGenesia.Actors.Survival.PrideBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_pride_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.SageLeafCD", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sage_leaf_c_d.html", null ],
      [ "RogueGenesia.Actors.Survival.SageLeafEffect", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sage_leaf_effect.html", null ],
      [ "RogueGenesia.Actors.Survival.SilphBlessing", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_silph_blessing.html", null ],
      [ "RogueGenesia.Actors.Survival.SlothBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sloth_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.SolaBlessing", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sola_blessing.html", null ],
      [ "RogueGenesia.Actors.Survival.SpeedFromDashBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_speed_from_dash_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.SplitReloadCD", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_split_reload_c_d.html", null ],
      [ "RogueGenesia.Actors.Survival.SynchronisedProjectileBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_synchronised_projectile_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.ThornTalentBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_thorn_talent_buff.html", null ],
      [ "RogueGenesia.Actors.Survival.TickingBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_ticking_buff.html", [
        [ "RogueGenesia.Actors.Survival.DamageOverTimeDebuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_damage_over_time_debuff.html", [
          [ "RogueGenesia.Actors.Survival.PoisonousDebuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_poisonous_debuff.html", null ]
        ] ]
      ] ],
      [ "RogueGenesia.Actors.Survival.WindLaceCD", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_wind_lace_c_d.html", null ],
      [ "RogueGenesia.Actors.Survival.WindLaceEffect", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_wind_lace_effect.html", null ],
      [ "RogueGenesia.Actors.Survival.WrathBuff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_wrath_buff.html", null ]
    ] ],
    [ "ModGenesia.BuffAPI", "class_mod_genesia_1_1_buff_a_p_i.html", null ],
    [ "RogueGenesia.Data.BuffIDManager", "class_rogue_genesia_1_1_data_1_1_buff_i_d_manager.html", null ],
    [ "ModGenesia.CardAPI", "class_mod_genesia_1_1_card_a_p_i.html", null ],
    [ "RogueGenesia.GameManager.CardWeightEventInfo", "class_rogue_genesia_1_1_game_manager_1_1_card_weight_event_info.html", null ],
    [ "ModGenesia.ChallengeAPI", "class_mod_genesia_1_1_challenge_a_p_i.html", null ],
    [ "RogueGenesia.Data.ChallengeData", "class_rogue_genesia_1_1_data_1_1_challenge_data.html", null ],
    [ "RogueGenesia.Data.ChallengeModifier", "class_rogue_genesia_1_1_data_1_1_challenge_modifier.html", null ],
    [ "RogueGenesia.Data.ChallengeSave", "class_rogue_genesia_1_1_data_1_1_challenge_save.html", null ],
    [ "RogueGenesia.Data.CModifierContainer< T >", "class_rogue_genesia_1_1_data_1_1_c_modifier_container.html", null ],
    [ "RogueGenesia.Actors.Survival.Collectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_collectible.html", [
      [ "RogueGenesia.Actors.Survival.AnachronisticCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_anachronistic_collectible.html", null ],
      [ "RogueGenesia.Actors.Survival.ChestCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_chest_collectible.html", null ],
      [ "RogueGenesia.Actors.Survival.GoldCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_gold_collectible.html", null ],
      [ "RogueGenesia.Actors.Survival.HealCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_heal_collectible.html", null ],
      [ "RogueGenesia.Actors.Survival.ObjectiveCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_objective_collectible.html", null ],
      [ "RogueGenesia.Actors.Survival.SoulPotionCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_soul_potion_collectible.html", null ],
      [ "RogueGenesia.Actors.Survival.SoulsCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_souls_collectible.html", null ],
      [ "RogueGenesia.Actors.Survival.VoidCollectible", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_void_collectible.html", null ]
    ] ],
    [ "RogueGenesia.Actors.Survival.DefaultProjectilAI.ColliderHitTime", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_default_projectil_a_i_1_1_collider_hit_time.html", null ],
    [ "ModGenesia.ContentAPI", "class_mod_genesia_1_1_content_a_p_i.html", null ],
    [ "RogueGenesia.Data.CustomChallengeDescription", "class_rogue_genesia_1_1_data_1_1_custom_challenge_description.html", null ],
    [ "RogueGenesia.Data.CustomChallengeModifier", "class_rogue_genesia_1_1_data_1_1_custom_challenge_modifier.html", null ],
    [ "RogueGenesia.Data.CustomDamageSource", "struct_rogue_genesia_1_1_data_1_1_custom_damage_source.html", null ],
    [ "RogueGenesia.Data.DamageData", "struct_rogue_genesia_1_1_data_1_1_damage_data.html", null ],
    [ "RogueGenesia.Actors.Survival.DamageInformation", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_damage_information.html", null ],
    [ "RogueGenesia.Actors.Survival.DamageMultiplierData", "struct_rogue_genesia_1_1_actors_1_1_survival_1_1_damage_multiplier_data.html", null ],
    [ "RogueGenesia.UI.DamageSourceContainer", "class_rogue_genesia_1_1_u_i_1_1_damage_source_container.html", null ],
    [ "RogueGenesia.UI.DamageText", "class_rogue_genesia_1_1_u_i_1_1_damage_text.html", null ],
    [ "RogueGenesia.Data.DataContainer< T >", "class_rogue_genesia_1_1_data_1_1_data_container.html", null ],
    [ "RogueGenesia.Data.DataContainer< float >", "class_rogue_genesia_1_1_data_1_1_data_container.html", null ],
    [ "RogueGenesia.GameManager.DeathStatue", "class_rogue_genesia_1_1_game_manager_1_1_death_statue.html", null ],
    [ "RogueGenesia.Data.DefaultRequirementClass", "class_rogue_genesia_1_1_data_1_1_default_requirement_class.html", [
      [ "RogueGenesia.Data.CardRequirement", "class_rogue_genesia_1_1_data_1_1_card_requirement.html", null ],
      [ "RogueGenesia.Data.StatRequirement", "class_rogue_genesia_1_1_data_1_1_stat_requirement.html", null ],
      [ "RogueGenesia.Data.WeaponTagRequirement", "class_rogue_genesia_1_1_data_1_1_weapon_tag_requirement.html", null ]
    ] ],
    [ "RogueGenesia.GameManager.DetailCardInfoHistory", "class_rogue_genesia_1_1_game_manager_1_1_detail_card_info_history.html", null ],
    [ "RogueGenesia.Data.EnemyAnimations", "class_rogue_genesia_1_1_data_1_1_enemy_animations.html", null ],
    [ "RogueGenesia.Data.EnemyModuleForSurvivors", "class_rogue_genesia_1_1_data_1_1_enemy_module_for_survivors.html", null ],
    [ "RogueGenesia.Data.EnemyStatMultiplier", "class_rogue_genesia_1_1_data_1_1_enemy_stat_multiplier.html", null ],
    [ "RogueGenesia.Data.EnemyTierContainer", "class_rogue_genesia_1_1_data_1_1_enemy_tier_container.html", null ],
    [ "RogueGenesia.Data.EnemyTierData", "class_rogue_genesia_1_1_data_1_1_enemy_tier_data.html", null ],
    [ "RogueGenesia.Data.EventRogue", "class_rogue_genesia_1_1_data_1_1_event_rogue.html", [
      [ "RogueGenesia.Data.BonFireEvent", "class_rogue_genesia_1_1_data_1_1_bon_fire_event.html", null ],
      [ "RogueGenesia.Data.DefaultEvent", "class_rogue_genesia_1_1_data_1_1_default_event.html", null ],
      [ "RogueGenesia.Data.GodStatuetteEvent", "class_rogue_genesia_1_1_data_1_1_god_statuette_event.html", null ],
      [ "RogueGenesia.Data.LegacyEvent", "class_rogue_genesia_1_1_data_1_1_legacy_event.html", null ],
      [ "RogueGenesia.Data.SaveVillagersEvent", "class_rogue_genesia_1_1_data_1_1_save_villagers_event.html", null ],
      [ "RogueGenesia.Data.SaveVillagersGiveCardEvent", "class_rogue_genesia_1_1_data_1_1_save_villagers_give_card_event.html", null ],
      [ "RogueGenesia.Data.ShopKeeperInvestmentEvent", "class_rogue_genesia_1_1_data_1_1_shop_keeper_investment_event.html", null ]
    ] ],
    [ "RogueGenesia.GameManager.FloatValue", "class_rogue_genesia_1_1_game_manager_1_1_float_value.html", null ],
    [ "RogueGenesia.Data.GameData", "class_rogue_genesia_1_1_data_1_1_game_data.html", null ],
    [ "RogueGenesia.Data.GameDataGetter", "class_rogue_genesia_1_1_data_1_1_game_data_getter.html", null ],
    [ "RogueGenesia.Data.GameDataSave", "class_rogue_genesia_1_1_data_1_1_game_data_save.html", null ],
    [ "RogueGenesia.GameManager.GameEventManager", "class_rogue_genesia_1_1_game_manager_1_1_game_event_manager.html", null ],
    [ "RogueGenesia.Data.GameHistoryManager", "class_rogue_genesia_1_1_data_1_1_game_history_manager.html", null ],
    [ "RogueGenesia.GameManager.GameManagerFight", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_fight.html", [
      [ "RogueGenesia.GameManager.GameManagerRogue", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_rogue.html", null ],
      [ "RogueGenesia.GameManager.GameManagerSurvival", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_survival.html", null ]
    ] ],
    [ "RogueGenesia.Data.GameModeClassInfo", "class_rogue_genesia_1_1_data_1_1_game_mode_class_info.html", [
      [ "RogueGenesia.Data.RogueModeClassInfo", "class_rogue_genesia_1_1_data_1_1_rogue_mode_class_info.html", null ],
      [ "RogueGenesia.Data.SurvivorsModeClassInfo", "class_rogue_genesia_1_1_data_1_1_survivors_mode_class_info.html", null ]
    ] ],
    [ "RogueGenesia.Data.GameModeDifficultyInfoClass", "class_rogue_genesia_1_1_data_1_1_game_mode_difficulty_info_class.html", null ],
    [ "RogueGenesia.UI.GameOptionData", "class_rogue_genesia_1_1_u_i_1_1_game_option_data.html", null ],
    [ "RogueGenesia.Data.GameRandom", "class_rogue_genesia_1_1_data_1_1_game_random.html", null ],
    [ "RogueGenesia.Data.GameStatCountainer", "class_rogue_genesia_1_1_data_1_1_game_stat_countainer.html", null ],
    [ "RogueGenesia.Save.GameStateSave", "class_rogue_genesia_1_1_save_1_1_game_state_save.html", null ],
    [ "RogueGenesia.UI.HitFX", "class_rogue_genesia_1_1_u_i_1_1_hit_f_x.html", null ],
    [ "IDeselectHandler", null, [
      [ "RogueGenesia.UI.OverButton", "class_rogue_genesia_1_1_u_i_1_1_over_button.html", null ]
    ] ],
    [ "RogueGenesia.Actors.Survival.IEntity", "interface_rogue_genesia_1_1_actors_1_1_survival_1_1_i_entity.html", [
      [ "RogueGenesia.Actors.Survival.CrateCollisionDetection", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_crate_collision_detection.html", [
        [ "RogueGenesia.Actors.Survival.GoldCactus", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_gold_cactus.html", null ]
      ] ],
      [ "RogueGenesia.Actors.Survival.DamageSourceEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_damage_source_entity.html", null ],
      [ "RogueGenesia.Actors.Survival.Monster", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_monster.html", [
        [ "RogueGenesia.Actors.Survival.ArcherMonster", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_archer_monster.html", null ],
        [ "RogueGenesia.Actors.Survival.EngineerMonster", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_engineer_monster.html", null ],
        [ "RogueGenesia.Actors.Survival.FolowingMonster", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_folowing_monster.html", null ],
        [ "RogueGenesia.Actors.Survival.ImmobileMonster", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_immobile_monster.html", null ],
        [ "RogueGenesia.Actors.Survival.MultiplicatorBoss", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_multiplicator_boss.html", null ],
        [ "RogueGenesia.Actors.Survival.NecroMancerBoss", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_mancer_boss.html", null ],
        [ "RogueGenesia.Actors.Survival.PathMonster", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_path_monster.html", null ],
        [ "RogueGenesia.Actors.Survival.ShamanBoss", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_shaman_boss.html", null ],
        [ "RogueGenesia.Actors.Survival.TurretMonster", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_turret_monster.html", null ],
        [ "RogueGenesia.Actors.Survival.WormBoss", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_worm_boss.html", null ]
      ] ],
      [ "RogueGenesia.Actors.Survival.MonsterCollisionDetection", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_monster_collision_detection.html", null ],
      [ "RogueGenesia.Actors.Survival.ObjectiveNPC", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_objective_n_p_c.html", null ],
      [ "RogueGenesia.Actors.Survival.PlayerEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_player_entity.html", null ]
    ] ],
    [ "IEnumerable", null, [
      [ "RogueGenesia.Data.StatisticContainer", "class_rogue_genesia_1_1_data_1_1_statistic_container.html", null ]
    ] ],
    [ "IMoveHandler", null, [
      [ "RogueGenesia.UI.ButtonSound", "class_rogue_genesia_1_1_u_i_1_1_button_sound.html", null ]
    ] ],
    [ "IPointerClickHandler", null, [
      [ "RogueGenesia.UI.ButtonSound", "class_rogue_genesia_1_1_u_i_1_1_button_sound.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "RogueGenesia.UI.ButtonSound", "class_rogue_genesia_1_1_u_i_1_1_button_sound.html", null ],
      [ "RogueGenesia.UI.OverButton", "class_rogue_genesia_1_1_u_i_1_1_over_button.html", null ],
      [ "RogueGenesia.UI.SelectOnMouseOver", "class_rogue_genesia_1_1_u_i_1_1_select_on_mouse_over.html", null ],
      [ "SoulShopUpgradePanel", "class_soul_shop_upgrade_panel.html", null ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "RogueGenesia.UI.OverButton", "class_rogue_genesia_1_1_u_i_1_1_over_button.html", null ],
      [ "SoulShopUpgradePanel", "class_soul_shop_upgrade_panel.html", null ]
    ] ],
    [ "ISelectHandler", null, [
      [ "RogueGenesia.UI.ButtonSound", "class_rogue_genesia_1_1_u_i_1_1_button_sound.html", null ],
      [ "RogueGenesia.UI.OverButton", "class_rogue_genesia_1_1_u_i_1_1_over_button.html", null ],
      [ "RogueGenesia.UI.SelectOnMouseOver", "class_rogue_genesia_1_1_u_i_1_1_select_on_mouse_over.html", null ]
    ] ],
    [ "RogueGenesia.Data.IStatEffector", "interface_rogue_genesia_1_1_data_1_1_i_stat_effector.html", [
      [ "RogueGenesia.Actors.Survival.Artifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_artifact.html", [
        [ "RogueGenesia.Actors.Survival.AdventurerLicenceArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_adventurer_licence_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.BattleRubyArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_battle_ruby_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.BeefStatueArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_beef_statue_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.BhikkhuPearlArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_bhikkhu_pearl_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.BrokenStatuetteArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_broken_statuette_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.ChampionBracerArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_champion_bracer_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.CheatingHandArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_cheating_hand_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.ChickenStatueArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_chicken_statue_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.CollectionBookArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_collection_book_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.CowardSaphirArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_coward_saphir_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.CursedBeltArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_cursed_belt_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.DiceArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_dice_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.GlassSwordArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_glass_sword_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.HermesHoodArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_hermes_hood_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.HolyCrossArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_holy_cross_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.LightningBootsArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_lightning_boots_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.MagnifyingGlassArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_magnifying_glass_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.MartyrCloakArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_martyr_cloak_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.MidasSwordArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_midas_sword_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.OldCoinArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_old_coin_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.OuroborosNecklaceArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_ouroboros_necklace_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.PhoenixTotemArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_phoenix_totem_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.PorkStatueArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_pork_statue_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.SacredSwordArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sacred_sword_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.SageLeafArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sage_leaf_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.SaintShinboneArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_saint_shinbone_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.SheepStatueArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sheep_statue_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.ShopKeeperPlateArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_shop_keeper_plate_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.SoulGauntletArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_soul_gauntlet_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.TrainingWeightArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_training_weight_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.TrollBloodArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_troll_blood_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.VoidStatueArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_void_statue_artifact.html", null ],
        [ "RogueGenesia.Actors.Survival.WindLaceArtifact", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_wind_lace_artifact.html", null ]
      ] ],
      [ "RogueGenesia.Data.SoulCard", "class_rogue_genesia_1_1_data_1_1_soul_card.html", [
        [ "RogueGenesia.Data.AmmoOnKill", "class_rogue_genesia_1_1_data_1_1_ammo_on_kill.html", null ],
        [ "RogueGenesia.Data.AttackSpeedOnDash", "class_rogue_genesia_1_1_data_1_1_attack_speed_on_dash.html", null ],
        [ "RogueGenesia.Data.AuraConversion", "class_rogue_genesia_1_1_data_1_1_aura_conversion.html", null ],
        [ "RogueGenesia.Data.Benediction", "class_rogue_genesia_1_1_data_1_1_benediction.html", null ],
        [ "RogueGenesia.Data.Berserker", "class_rogue_genesia_1_1_data_1_1_berserker.html", null ],
        [ "RogueGenesia.Data.DamageOnReload", "class_rogue_genesia_1_1_data_1_1_damage_on_reload.html", null ],
        [ "RogueGenesia.Data.DashChargeOnReload", "class_rogue_genesia_1_1_data_1_1_dash_charge_on_reload.html", null ],
        [ "RogueGenesia.Data.DashQuickReloading", "class_rogue_genesia_1_1_data_1_1_dash_quick_reloading.html", null ],
        [ "RogueGenesia.Data.DashReloading", "class_rogue_genesia_1_1_data_1_1_dash_reloading.html", null ],
        [ "RogueGenesia.Data.DefenceToDamageSoulCard", "class_rogue_genesia_1_1_data_1_1_defence_to_damage_soul_card.html", null ],
        [ "RogueGenesia.Data.Envy", "class_rogue_genesia_1_1_data_1_1_envy.html", null ],
        [ "RogueGenesia.Data.FightAndFlight", "class_rogue_genesia_1_1_data_1_1_fight_and_flight.html", null ],
        [ "RogueGenesia.Data.FireOnDash", "class_rogue_genesia_1_1_data_1_1_fire_on_dash.html", null ],
        [ "RogueGenesia.Data.Gluttony", "class_rogue_genesia_1_1_data_1_1_gluttony.html", null ],
        [ "RogueGenesia.Data.Greed", "class_rogue_genesia_1_1_data_1_1_greed.html", null ],
        [ "RogueGenesia.Data.HealthToDamageSoulCard", "class_rogue_genesia_1_1_data_1_1_health_to_damage_soul_card.html", null ],
        [ "RogueGenesia.Data.Immovable", "class_rogue_genesia_1_1_data_1_1_immovable.html", null ],
        [ "RogueGenesia.Data.Lust", "class_rogue_genesia_1_1_data_1_1_lust.html", null ],
        [ "RogueGenesia.Data.NegativeArmorIsDamage", "class_rogue_genesia_1_1_data_1_1_negative_armor_is_damage.html", null ],
        [ "RogueGenesia.Data.PlayerModifierSoulCard", "class_rogue_genesia_1_1_data_1_1_player_modifier_soul_card.html", null ],
        [ "RogueGenesia.Data.Pride", "class_rogue_genesia_1_1_data_1_1_pride.html", null ],
        [ "RogueGenesia.Data.ProjectileModifierSoulCard", "class_rogue_genesia_1_1_data_1_1_projectile_modifier_soul_card.html", null ],
        [ "RogueGenesia.Data.ProjectileShield", "class_rogue_genesia_1_1_data_1_1_projectile_shield.html", null ],
        [ "RogueGenesia.Data.Pyromaniac", "class_rogue_genesia_1_1_data_1_1_pyromaniac.html", null ],
        [ "RogueGenesia.Data.ReactiveTrigger", "class_rogue_genesia_1_1_data_1_1_reactive_trigger.html", null ],
        [ "RogueGenesia.Data.Rift", "class_rogue_genesia_1_1_data_1_1_rift.html", null ],
        [ "RogueGenesia.Data.Sloth", "class_rogue_genesia_1_1_data_1_1_sloth.html", null ],
        [ "RogueGenesia.Data.SpeedOnDash", "class_rogue_genesia_1_1_data_1_1_speed_on_dash.html", null ],
        [ "RogueGenesia.Data.SpikeBoots", "class_rogue_genesia_1_1_data_1_1_spike_boots.html", null ],
        [ "RogueGenesia.Data.SplitProjectileOnReload", "class_rogue_genesia_1_1_data_1_1_split_projectile_on_reload.html", null ],
        [ "RogueGenesia.Data.StatSoulCard", "class_rogue_genesia_1_1_data_1_1_stat_soul_card.html", null ],
        [ "RogueGenesia.Data.TriggerAmulet", "class_rogue_genesia_1_1_data_1_1_trigger_amulet.html", null ],
        [ "RogueGenesia.Data.VoidSpiritEffect", "class_rogue_genesia_1_1_data_1_1_void_spirit_effect.html", null ],
        [ "RogueGenesia.Data.WeaponSoulCard", "class_rogue_genesia_1_1_data_1_1_weapon_soul_card.html", null ],
        [ "RogueGenesia.Data.Wrath", "class_rogue_genesia_1_1_data_1_1_wrath.html", null ]
      ] ],
      [ "RogueGenesia.Data.Talent", "class_rogue_genesia_1_1_data_1_1_talent.html", [
        [ "RogueGenesia.Data.ActiveTalent", "class_rogue_genesia_1_1_data_1_1_active_talent.html", [
          [ "RogueGenesia.Data.BowTalent", "class_rogue_genesia_1_1_data_1_1_bow_talent.html", null ],
          [ "RogueGenesia.Data.CleaverTalent", "class_rogue_genesia_1_1_data_1_1_cleaver_talent.html", null ],
          [ "RogueGenesia.Data.CrossbowTalent", "class_rogue_genesia_1_1_data_1_1_crossbow_talent.html", null ],
          [ "RogueGenesia.Data.DeathAuraTalent", "class_rogue_genesia_1_1_data_1_1_death_aura_talent.html", null ],
          [ "RogueGenesia.Data.ExplosiveVialTalent", "class_rogue_genesia_1_1_data_1_1_explosive_vial_talent.html", null ],
          [ "RogueGenesia.Data.FireRingTalent", "class_rogue_genesia_1_1_data_1_1_fire_ring_talent.html", null ],
          [ "RogueGenesia.Data.GunSlingerTalent", "class_rogue_genesia_1_1_data_1_1_gun_slinger_talent.html", null ],
          [ "RogueGenesia.Data.KatanaTalent", "class_rogue_genesia_1_1_data_1_1_katana_talent.html", null ],
          [ "RogueGenesia.Data.KunaiTalent", "class_rogue_genesia_1_1_data_1_1_kunai_talent.html", null ],
          [ "RogueGenesia.Data.MagicWandTalent", "class_rogue_genesia_1_1_data_1_1_magic_wand_talent.html", null ],
          [ "RogueGenesia.Data.MagicWispTalent", "class_rogue_genesia_1_1_data_1_1_magic_wisp_talent.html", null ],
          [ "RogueGenesia.Data.PikeTalent", "class_rogue_genesia_1_1_data_1_1_pike_talent.html", null ],
          [ "RogueGenesia.Data.ShamanStaffTalent", "class_rogue_genesia_1_1_data_1_1_shaman_staff_talent.html", null ],
          [ "RogueGenesia.Data.ShurikenTalent", "class_rogue_genesia_1_1_data_1_1_shuriken_talent.html", null ],
          [ "RogueGenesia.Data.SpearTalent", "class_rogue_genesia_1_1_data_1_1_spear_talent.html", null ],
          [ "RogueGenesia.Data.SwordrangTalent", "class_rogue_genesia_1_1_data_1_1_swordrang_talent.html", null ],
          [ "RogueGenesia.Data.ThornTalent", "class_rogue_genesia_1_1_data_1_1_thorn_talent.html", null ],
          [ "RogueGenesia.Data.ThrowingKnifeTalent", "class_rogue_genesia_1_1_data_1_1_throwing_knife_talent.html", null ],
          [ "RogueGenesia.Data.ThunderStaffTalent", "class_rogue_genesia_1_1_data_1_1_thunder_staff_talent.html", null ],
          [ "RogueGenesia.Data.WindBladeTalent", "class_rogue_genesia_1_1_data_1_1_wind_blade_talent.html", null ],
          [ "RogueGenesia.Data.WormGlandTalent", "class_rogue_genesia_1_1_data_1_1_worm_gland_talent.html", null ]
        ] ],
        [ "RogueGenesia.Data.PassiveTalent", "class_rogue_genesia_1_1_data_1_1_passive_talent.html", [
          [ "RogueGenesia.Data.AnachronisticHourglassTalent", "class_rogue_genesia_1_1_data_1_1_anachronistic_hourglass_talent.html", null ],
          [ "RogueGenesia.Data.DesynchronisedHeartTalent", "class_rogue_genesia_1_1_data_1_1_desynchronised_heart_talent.html", null ],
          [ "RogueGenesia.Data.FieryStoneTalent", "class_rogue_genesia_1_1_data_1_1_fiery_stone_talent.html", null ],
          [ "RogueGenesia.Data.FireStoneTalent", "class_rogue_genesia_1_1_data_1_1_fire_stone_talent.html", null ],
          [ "RogueGenesia.Data.GaleStoneTalent", "class_rogue_genesia_1_1_data_1_1_gale_stone_talent.html", null ],
          [ "RogueGenesia.Data.GilgameshLegacyTalent", "class_rogue_genesia_1_1_data_1_1_gilgamesh_legacy_talent.html", null ],
          [ "RogueGenesia.Data.LunarStoneTalent", "class_rogue_genesia_1_1_data_1_1_lunar_stone_talent.html", null ],
          [ "RogueGenesia.Data.MoonStoneTalent", "class_rogue_genesia_1_1_data_1_1_moon_stone_talent.html", null ],
          [ "RogueGenesia.Data.MultiShotTalent", "class_rogue_genesia_1_1_data_1_1_multi_shot_talent.html", null ],
          [ "RogueGenesia.Data.SolarStoneTalent", "class_rogue_genesia_1_1_data_1_1_solar_stone_talent.html", null ],
          [ "RogueGenesia.Data.StelarStoneTalent", "class_rogue_genesia_1_1_data_1_1_stelar_stone_talent.html", null ],
          [ "RogueGenesia.Data.SunStoneTalent", "class_rogue_genesia_1_1_data_1_1_sun_stone_talent.html", null ],
          [ "RogueGenesia.Data.SynchronisedProjectileTalent", "class_rogue_genesia_1_1_data_1_1_synchronised_projectile_talent.html", null ],
          [ "RogueGenesia.Data.TaintedSealTalent", "class_rogue_genesia_1_1_data_1_1_tainted_seal_talent.html", null ],
          [ "RogueGenesia.Data.WindStoneTalent", "class_rogue_genesia_1_1_data_1_1_wind_stone_talent.html", null ]
        ] ]
      ] ]
    ] ],
    [ "ISubmitHandler", null, [
      [ "RogueGenesia.UI.ButtonSound", "class_rogue_genesia_1_1_u_i_1_1_button_sound.html", null ]
    ] ],
    [ "KatanaVisual", null, [
      [ "RogueGenesia.Actors.Survival.FieryDashAOE", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_fiery_dash_a_o_e.html", null ],
      [ "RogueGenesia.Actors.Survival.FireKatanaAOE", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_fire_katana_a_o_e.html", null ]
    ] ],
    [ "RogueGenesia.Data.LevelObject", "class_rogue_genesia_1_1_data_1_1_level_object.html", null ],
    [ "RogueGenesia.Save.LevelObjectSave", "class_rogue_genesia_1_1_save_1_1_level_object_save.html", null ],
    [ "RogueGenesia.Data.ListCleaner< T >", "class_rogue_genesia_1_1_data_1_1_list_cleaner.html", null ],
    [ "RogueGenesia.Data.LocalizationData", "class_rogue_genesia_1_1_data_1_1_localization_data.html", null ],
    [ "RogueGenesia.Data.LocalizationDataList", "class_rogue_genesia_1_1_data_1_1_localization_data_list.html", null ],
    [ "RogueGenesia.Data.Loot", "struct_rogue_genesia_1_1_data_1_1_loot.html", null ],
    [ "ModGenesia.ModCardRequirement", "class_mod_genesia_1_1_mod_card_requirement.html", null ],
    [ "ModGenesia.ModData", "class_mod_genesia_1_1_mod_data.html", null ],
    [ "RogueGenesia.Data.ModdedGameData", "class_rogue_genesia_1_1_data_1_1_modded_game_data.html", null ],
    [ "RogueGenesia.Data.ModdedStatsContainer", "class_rogue_genesia_1_1_data_1_1_modded_stats_container.html", null ],
    [ "ModGenesia.ModGenesia", "class_mod_genesia_1_1_mod_genesia.html", null ],
    [ "RogueGenesia.Data.ModifierLevel", "class_rogue_genesia_1_1_data_1_1_modifier_level.html", null ],
    [ "RogueGenesia.Save.ModifierSave", "class_rogue_genesia_1_1_save_1_1_modifier_save.html", null ],
    [ "ModGenesia.ModInfo", "class_mod_genesia_1_1_mod_info.html", null ],
    [ "ModGenesia.SteamWorkShop.ModInstallInfo", "class_mod_genesia_1_1_steam_work_shop_1_1_mod_install_info.html", null ],
    [ "ModGenesia.ModLoader", "class_mod_genesia_1_1_mod_loader.html", null ],
    [ "ModGenesia.ModOption", "class_mod_genesia_1_1_mod_option.html", null ],
    [ "ModGenesia.ModVersion", "class_mod_genesia_1_1_mod_version.html", null ],
    [ "MonoBehaviour", null, [
      [ "AchievementNotification", "class_achievement_notification.html", null ],
      [ "ChargeUI", "class_charge_u_i.html", null ],
      [ "DashChargeUI", "class_dash_charge_u_i.html", null ],
      [ "FontSizeManager", "class_font_size_manager.html", null ],
      [ "GeneralStats", "class_general_stats.html", null ],
      [ "InputCheck", "class_input_check.html", null ],
      [ "MapIcon", "class_map_icon.html", null ],
      [ "ModButton", "class_mod_button.html", null ],
      [ "ModGenesia.ModListManager", "class_mod_genesia_1_1_mod_list_manager.html", null ],
      [ "ProceduralPlacedObject", "class_procedural_placed_object.html", [
        [ "RogueGenesia.Actors.Survival.CrateCollisionDetection", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_crate_collision_detection.html", null ],
        [ "RogueGenesia.Actors.Survival.DamageSourceEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_damage_source_entity.html", null ]
      ] ],
      [ "Rebind", "class_rebind.html", null ],
      [ "RebindData", "class_rebind_data.html", null ],
      [ "RogueGenesia.AchievementManager", "class_rogue_genesia_1_1_achievement_manager.html", null ],
      [ "RogueGenesia.Actors.Map.StageSelectionManager", "class_rogue_genesia_1_1_actors_1_1_map_1_1_stage_selection_manager.html", null ],
      [ "RogueGenesia.Actors.PlayerController", "class_rogue_genesia_1_1_actors_1_1_player_controller.html", null ],
      [ "RogueGenesia.Actors.Survival.AchievementTrigger", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_achievement_trigger.html", null ],
      [ "RogueGenesia.Actors.Survival.ActivableEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_activable_entity.html", [
        [ "RogueGenesia.Actors.Survival.AltarEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_altar_entity.html", null ],
        [ "RogueGenesia.Actors.Survival.ShrineEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_shrine_entity.html", null ]
      ] ],
      [ "RogueGenesia.Actors.Survival.CameraScript", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_camera_script.html", null ],
      [ "RogueGenesia.Actors.Survival.MonsterCollisionDetection", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_monster_collision_detection.html", null ],
      [ "RogueGenesia.Actors.Survival.ObjectiveNPC", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_objective_n_p_c.html", null ],
      [ "RogueGenesia.Actors.Survival.Pet", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_pet.html", null ],
      [ "RogueGenesia.Actors.Survival.PlayerControllerSurvival", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_player_controller_survival.html", null ],
      [ "RogueGenesia.Actors.Survival.PlayerEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_player_entity.html", null ],
      [ "RogueGenesia.Actors.Survival.ProjectileCollisionDetection", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_projectile_collision_detection.html", null ],
      [ "RogueGenesia.Data.AchievementMenuData", "class_rogue_genesia_1_1_data_1_1_achievement_menu_data.html", null ],
      [ "RogueGenesia.Data.LevelData", "class_rogue_genesia_1_1_data_1_1_level_data.html", null ],
      [ "RogueGenesia.GameManager.CollectibleManager", "class_rogue_genesia_1_1_game_manager_1_1_collectible_manager.html", null ],
      [ "RogueGenesia.GameManager.DiscordManager", "class_rogue_genesia_1_1_game_manager_1_1_discord_manager.html", null ],
      [ "RogueGenesia.GameManager.EnemyManager", "class_rogue_genesia_1_1_game_manager_1_1_enemy_manager.html", null ],
      [ "RogueGenesia.GameManager.FXManager", "class_rogue_genesia_1_1_game_manager_1_1_f_x_manager.html", null ],
      [ "RogueGenesia.GameManager.GamePlayManager", "class_rogue_genesia_1_1_game_manager_1_1_game_play_manager.html", null ],
      [ "RogueGenesia.GameManager.MouseCursorManager", "class_rogue_genesia_1_1_game_manager_1_1_mouse_cursor_manager.html", null ],
      [ "RogueGenesia.GameManager.ProceduralObjectPlacement", "class_rogue_genesia_1_1_game_manager_1_1_procedural_object_placement.html", null ],
      [ "RogueGenesia.GameManager.ProjectileManager", "class_rogue_genesia_1_1_game_manager_1_1_projectile_manager.html", null ],
      [ "RogueGenesia.GameManager.SoundManager", "class_rogue_genesia_1_1_game_manager_1_1_sound_manager.html", null ],
      [ "RogueGenesia.Save.SaveManager", "class_rogue_genesia_1_1_save_1_1_save_manager.html", null ],
      [ "RogueGenesia.UI.AchievementMenu", "class_rogue_genesia_1_1_u_i_1_1_achievement_menu.html", null ],
      [ "RogueGenesia.UI.AmmoCounter", "class_rogue_genesia_1_1_u_i_1_1_ammo_counter.html", null ],
      [ "RogueGenesia.UI.ArtifactDetail", "class_rogue_genesia_1_1_u_i_1_1_artifact_detail.html", null ],
      [ "RogueGenesia.UI.ArtifactSelectionUI", "class_rogue_genesia_1_1_u_i_1_1_artifact_selection_u_i.html", null ],
      [ "RogueGenesia.UI.AvatarUI", "class_rogue_genesia_1_1_u_i_1_1_avatar_u_i.html", null ],
      [ "RogueGenesia.UI.BuffUIContainer", "class_rogue_genesia_1_1_u_i_1_1_buff_u_i_container.html", null ],
      [ "RogueGenesia.UI.BuffUIManager", "class_rogue_genesia_1_1_u_i_1_1_buff_u_i_manager.html", null ],
      [ "RogueGenesia.UI.ButtonSound", "class_rogue_genesia_1_1_u_i_1_1_button_sound.html", null ],
      [ "RogueGenesia.UI.BuyButton", "class_rogue_genesia_1_1_u_i_1_1_buy_button.html", null ],
      [ "RogueGenesia.UI.ChoiceUI", "class_rogue_genesia_1_1_u_i_1_1_choice_u_i.html", null ],
      [ "RogueGenesia.UI.DamageSourceUI", "class_rogue_genesia_1_1_u_i_1_1_damage_source_u_i.html", null ],
      [ "RogueGenesia.UI.DetailedCardInformationUI", "class_rogue_genesia_1_1_u_i_1_1_detailed_card_information_u_i.html", null ],
      [ "RogueGenesia.UI.GameHistoryDetails", "class_rogue_genesia_1_1_u_i_1_1_game_history_details.html", null ],
      [ "RogueGenesia.UI.GameHistoryPannel", "class_rogue_genesia_1_1_u_i_1_1_game_history_pannel.html", null ],
      [ "RogueGenesia.UI.GameHistoryTab", "class_rogue_genesia_1_1_u_i_1_1_game_history_tab.html", null ],
      [ "RogueGenesia.UI.GameOptionManager", "class_rogue_genesia_1_1_u_i_1_1_game_option_manager.html", null ],
      [ "RogueGenesia.UI.GameOption_UI", "class_rogue_genesia_1_1_u_i_1_1_game_option___u_i.html", null ],
      [ "RogueGenesia.UI.GameStatsPannel", "class_rogue_genesia_1_1_u_i_1_1_game_stats_pannel.html", null ],
      [ "RogueGenesia.UI.GlobalToolTipManager", "class_rogue_genesia_1_1_u_i_1_1_global_tool_tip_manager.html", null ],
      [ "RogueGenesia.UI.InGameTalentUI", "class_rogue_genesia_1_1_u_i_1_1_in_game_talent_u_i.html", null ],
      [ "RogueGenesia.UI.MenuManager", "class_rogue_genesia_1_1_u_i_1_1_menu_manager.html", [
        [ "RogueGenesia.GameManager.DetailedCardInformationManager", "class_rogue_genesia_1_1_game_manager_1_1_detailed_card_information_manager.html", null ],
        [ "RogueGenesia.GameManager.GameEndManager", "class_rogue_genesia_1_1_game_manager_1_1_game_end_manager.html", null ],
        [ "RogueGenesia.GameManager.SoulShopManager", "class_rogue_genesia_1_1_game_manager_1_1_soul_shop_manager.html", null ],
        [ "RogueGenesia.GameManager.SpecialManager", "class_rogue_genesia_1_1_game_manager_1_1_special_manager.html", [
          [ "RogueGenesia.GameManager.Menu.EventManager", "class_rogue_genesia_1_1_game_manager_1_1_menu_1_1_event_manager.html", null ],
          [ "RogueGenesia.GameManager.RewardManager", "class_rogue_genesia_1_1_game_manager_1_1_reward_manager.html", null ],
          [ "RogueGenesia.GameManager.ShopManager", "class_rogue_genesia_1_1_game_manager_1_1_shop_manager.html", [
            [ "RogueGenesia.GameManager.NormalShop", "class_rogue_genesia_1_1_game_manager_1_1_normal_shop.html", [
              [ "RogueGenesia.GameManager.BlackSmith", "class_rogue_genesia_1_1_game_manager_1_1_black_smith.html", null ]
            ] ],
            [ "RogueGenesia.GameManager.ShopKeeperShopManager", "class_rogue_genesia_1_1_game_manager_1_1_shop_keeper_shop_manager.html", null ]
          ] ]
        ] ],
        [ "RogueGenesia.UI.AvatarSelectionMenu", "class_rogue_genesia_1_1_u_i_1_1_avatar_selection_menu.html", null ],
        [ "RogueGenesia.UI.MainMenuManager", "class_rogue_genesia_1_1_u_i_1_1_main_menu_manager.html", null ],
        [ "RogueGenesia.UI.OptionMenu", "class_rogue_genesia_1_1_u_i_1_1_option_menu.html", null ],
        [ "RogueGenesia.UI.PauseMenu", "class_rogue_genesia_1_1_u_i_1_1_pause_menu.html", null ],
        [ "RogueGenesia.UI.PetSelection", "class_rogue_genesia_1_1_u_i_1_1_pet_selection.html", null ],
        [ "RogueGenesia.UI.ProfileManager", "class_rogue_genesia_1_1_u_i_1_1_profile_manager.html", null ],
        [ "RogueGenesia.UI.StartGameManager", "class_rogue_genesia_1_1_u_i_1_1_start_game_manager.html", null ],
        [ "RogueGenesia.UI.StatsMenu", "class_rogue_genesia_1_1_u_i_1_1_stats_menu.html", null ],
        [ "RogueGenesia.UI.TalentSelectionMenu", "class_rogue_genesia_1_1_u_i_1_1_talent_selection_menu.html", null ],
        [ "RogueGenesia.UI.UILevelUp", "class_rogue_genesia_1_1_u_i_1_1_u_i_level_up.html", null ]
      ] ],
      [ "RogueGenesia.UI.OverButton", "class_rogue_genesia_1_1_u_i_1_1_over_button.html", null ],
      [ "RogueGenesia.UI.PetUI", "class_rogue_genesia_1_1_u_i_1_1_pet_u_i.html", null ],
      [ "RogueGenesia.UI.ProfileButton", "class_rogue_genesia_1_1_u_i_1_1_profile_button.html", null ],
      [ "RogueGenesia.UI.RewardButton", "class_rogue_genesia_1_1_u_i_1_1_reward_button.html", null ],
      [ "RogueGenesia.UI.SelectOnMouseOver", "class_rogue_genesia_1_1_u_i_1_1_select_on_mouse_over.html", null ],
      [ "RogueGenesia.UI.SoulCardUI", "class_rogue_genesia_1_1_u_i_1_1_soul_card_u_i.html", null ],
      [ "RogueGenesia.UI.StatsPannel", "class_rogue_genesia_1_1_u_i_1_1_stats_pannel.html", null ],
      [ "RogueGenesia.UI.TabScript", "class_rogue_genesia_1_1_u_i_1_1_tab_script.html", null ],
      [ "RogueGenesia.UI.TalentUI", "class_rogue_genesia_1_1_u_i_1_1_talent_u_i.html", null ],
      [ "RogueGenesia.Utils.PrefabPooling", "class_rogue_genesia_1_1_utils_1_1_prefab_pooling.html", [
        [ "RogueGenesia.Pooling.ProjectilPooling", "class_rogue_genesia_1_1_pooling_1_1_projectil_pooling.html", null ]
      ] ],
      [ "Singleton", "class_singleton.html", null ],
      [ "SlotSelect_UI", "class_slot_select___u_i.html", null ],
      [ "SoulCardLevelUpDetails", "class_soul_card_level_up_details.html", null ],
      [ "SoulShopUpgradePanel", "class_soul_shop_upgrade_panel.html", null ],
      [ "SteamManager", "class_steam_manager.html", null ],
      [ "UnityEngine.UI.CustomBar", "class_unity_engine_1_1_u_i_1_1_custom_bar.html", null ],
      [ "UnityEngine.UI.Extensions.UIScrollToSelection", "class_unity_engine_1_1_u_i_1_1_extensions_1_1_u_i_scroll_to_selection.html", null ],
      [ "VersionGetter", "class_version_getter.html", null ]
    ] ],
    [ "RogueGenesia.Data.MonsterAbility", "class_rogue_genesia_1_1_data_1_1_monster_ability.html", [
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.BuffShamanAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_buff_shaman_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.FractalBallsAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_fractal_balls_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.LazorShamanAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_lazor_shaman_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.ShamanBlink", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_blink.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.ShamanBlinkStorm", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_blink_storm.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.ShamanMagicBullet", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_magic_bullet.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.ShamanMagicBulletStorm", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_shaman_magic_bullet_storm.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Shaman.SummonGoblinAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_shaman_1_1_summon_goblin_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Worm.DashWormAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_worm_1_1_dash_worm_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Worm.SpitWormAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_worm_1_1_spit_worm_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.BossAbility.Worm.SummonWormAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boss_ability_1_1_worm_1_1_summon_worm_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.NecroEndFlyAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_end_fly_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.NecroMagicMissileFlyAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_magic_missile_fly_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.NecroPlaneteryProjWalkAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_planetery_proj_walk_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.NecroSpitFlyAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_spit_fly_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.NecroStartFlyAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_start_fly_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.NecroSummonFlyAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_summon_fly_ability.html", null ],
      [ "RogueGenesia.Actors.Survival.NecroSummonWalkAbility", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_necro_summon_walk_ability.html", null ],
      [ "RogueGenesia.Data.GeneralAbility", "class_rogue_genesia_1_1_data_1_1_general_ability.html", [
        [ "RogueGenesia.Data.AgileAbility", "class_rogue_genesia_1_1_data_1_1_agile_ability.html", null ],
        [ "RogueGenesia.Data.BerserkerAbility", "class_rogue_genesia_1_1_data_1_1_berserker_ability.html", null ],
        [ "RogueGenesia.Data.LifeLink", "class_rogue_genesia_1_1_data_1_1_life_link.html", null ],
        [ "RogueGenesia.Data.LifeRegen", "class_rogue_genesia_1_1_data_1_1_life_regen.html", null ],
        [ "RogueGenesia.Data.MartyrAbility", "class_rogue_genesia_1_1_data_1_1_martyr_ability.html", null ],
        [ "RogueGenesia.Data.PoisonousAbility", "class_rogue_genesia_1_1_data_1_1_poisonous_ability.html", null ],
        [ "RogueGenesia.Data.ProphetAbility", "class_rogue_genesia_1_1_data_1_1_prophet_ability.html", null ],
        [ "RogueGenesia.Data.RiftedAbility", "class_rogue_genesia_1_1_data_1_1_rifted_ability.html", null ],
        [ "RogueGenesia.Data.SplitOnDeath", "class_rogue_genesia_1_1_data_1_1_split_on_death.html", [
          [ "RogueGenesia.Data.SplitOnDeath8", "class_rogue_genesia_1_1_data_1_1_split_on_death8.html", null ]
        ] ],
        [ "RogueGenesia.Data.VampireAbility", "class_rogue_genesia_1_1_data_1_1_vampire_ability.html", null ]
      ] ]
    ] ],
    [ "RogueGenesia.Data.MonsterTypeSave", "class_rogue_genesia_1_1_data_1_1_monster_type_save.html", null ],
    [ "RogueGenesia.Data.MonsterTypeTierContainer", "class_rogue_genesia_1_1_data_1_1_monster_type_tier_container.html", null ],
    [ "RogueGenesia.Data.MonsterTypeZoneContainer", "class_rogue_genesia_1_1_data_1_1_monster_type_zone_container.html", null ],
    [ "RogueGenesia.Data.NameToConstructor", "struct_rogue_genesia_1_1_data_1_1_name_to_constructor.html", null ],
    [ "RogueGenesia.Data.OldGameDataSave", "class_rogue_genesia_1_1_data_1_1_old_game_data_save.html", null ],
    [ "OptionData", "class_option_data.html", null ],
    [ "RogueGenesia.UI.PannelNavigationHelper", "class_rogue_genesia_1_1_u_i_1_1_pannel_navigation_helper.html", null ],
    [ "RogueGenesia.Data.PatternModuleForSurvivors", "class_rogue_genesia_1_1_data_1_1_pattern_module_for_survivors.html", null ],
    [ "RogueGenesia.Data.PersistantGameSave", "class_rogue_genesia_1_1_data_1_1_persistant_game_save.html", null ],
    [ "RogueGenesia.Save.PersistantSaveManager", "class_rogue_genesia_1_1_save_1_1_persistant_save_manager.html", null ],
    [ "RogueGenesia.Data.PetAnimations", "class_rogue_genesia_1_1_data_1_1_pet_animations.html", null ],
    [ "RogueGenesia.Data.PetBehaviour", "class_rogue_genesia_1_1_data_1_1_pet_behaviour.html", [
      [ "RogueGenesia.Data.IdlePetBehaviour", "class_rogue_genesia_1_1_data_1_1_idle_pet_behaviour.html", null ],
      [ "RogueGenesia.Data.MoveToADifferentPositionPetBehaviour", "class_rogue_genesia_1_1_data_1_1_move_to_a_different_position_pet_behaviour.html", null ]
    ] ],
    [ "RogueGenesia.Data.PetContainer", "class_rogue_genesia_1_1_data_1_1_pet_container.html", null ],
    [ "RogueGenesia.Data.PetData", "class_rogue_genesia_1_1_data_1_1_pet_data.html", [
      [ "RogueGenesia.Data.CatPetData", "class_rogue_genesia_1_1_data_1_1_cat_pet_data.html", null ],
      [ "RogueGenesia.Data.DogPetData", "class_rogue_genesia_1_1_data_1_1_dog_pet_data.html", null ]
    ] ],
    [ "RogueGenesia.Data.PixelAnimationData", "class_rogue_genesia_1_1_data_1_1_pixel_animation_data.html", null ],
    [ "RogueGenesia.Save.PlayerSave", "class_rogue_genesia_1_1_save_1_1_player_save.html", null ],
    [ "RogueGenesia.Data.PlayerSSUData", "class_rogue_genesia_1_1_data_1_1_player_s_s_u_data.html", null ],
    [ "RogueGenesia.Data.PlayerStats", "class_rogue_genesia_1_1_data_1_1_player_stats.html", null ],
    [ "RogueGenesia.Utils.Poolable", "class_rogue_genesia_1_1_utils_1_1_poolable.html", [
      [ "RogueGenesia.Actors.Survival.DefaultProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_default_projectil_a_i.html", [
        [ "RogueGenesia.Actors.Survival.AirGroundMissibleAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_air_ground_missible_a_i.html", null ],
        [ "RogueGenesia.Actors.Survival.BouncyProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_bouncy_projectil_a_i.html", null ],
        [ "RogueGenesia.Actors.Survival.DoNothingProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_do_nothing_projectil_a_i.html", null ],
        [ "RogueGenesia.Actors.Survival.ExpandingAOEAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_expanding_a_o_e_a_i.html", null ],
        [ "RogueGenesia.Actors.Survival.GravityProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_gravity_projectil_a_i.html", null ],
        [ "RogueGenesia.Actors.Survival.GuidedProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_guided_projectil_a_i.html", [
          [ "RogueGenesia.Actors.Survival.BoomerangProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_boomerang_projectil_a_i.html", null ]
        ] ],
        [ "RogueGenesia.Actors.Survival.OrbitalProjectileAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_orbital_projectile_a_i.html", null ],
        [ "RogueGenesia.Actors.Survival.PikeProjectileAi", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_pike_projectile_ai.html", null ],
        [ "RogueGenesia.Actors.Survival.PlanetaryProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_planetary_projectil_a_i.html", null ],
        [ "RogueGenesia.Actors.Survival.WispProjectilAI", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_wisp_projectil_a_i.html", null ]
      ] ]
    ] ],
    [ "RogueGenesia.Utils.PoolingOnePrefab", "class_rogue_genesia_1_1_utils_1_1_pooling_one_prefab.html", null ],
    [ "RogueGenesia.Actors.Survival.PositionAtTime", "struct_rogue_genesia_1_1_actors_1_1_survival_1_1_position_at_time.html", null ],
    [ "RogueGenesia.Data.PrevGameDataSave", "class_rogue_genesia_1_1_data_1_1_prev_game_data_save.html", null ],
    [ "RogueGenesia.Data.PreviousGameData", "class_rogue_genesia_1_1_data_1_1_previous_game_data.html", null ],
    [ "RogueGenesia.Data.PreviousGameDataList", "class_rogue_genesia_1_1_data_1_1_previous_game_data_list.html", null ],
    [ "RogueGenesia.Data.PreviousPlayerStats", "class_rogue_genesia_1_1_data_1_1_previous_player_stats.html", null ],
    [ "RogueGenesia.Data.ProceduralObjectCountainer", "class_rogue_genesia_1_1_data_1_1_procedural_object_countainer.html", null ],
    [ "RogueGenesia.Data.ProceduralSector", "class_rogue_genesia_1_1_data_1_1_procedural_sector.html", null ],
    [ "PropertyAttribute", null, [
      [ "EnumFlagAttribute", "class_enum_flag_attribute.html", null ],
      [ "RogueGenesia.Data.EnemyStat", "class_rogue_genesia_1_1_data_1_1_enemy_stat.html", null ]
    ] ],
    [ "RogueGenesia.Data.RandomExtensions", "class_rogue_genesia_1_1_data_1_1_random_extensions.html", null ],
    [ "RogueGenesia.Data.RandomState", "struct_rogue_genesia_1_1_data_1_1_random_state.html", null ],
    [ "RogueGenesia.GameManager.RecentSoundContainer", "class_rogue_genesia_1_1_game_manager_1_1_recent_sound_container.html", null ],
    [ "RogueGenesia.RGRichText", "class_rogue_genesia_1_1_r_g_rich_text.html", null ],
    [ "RogueGenesia.RGUtils", "class_rogue_genesia_1_1_r_g_utils.html", null ],
    [ "RogueGenesia.Data.FireRingTalent.RingFireGO", "class_rogue_genesia_1_1_data_1_1_fire_ring_talent_1_1_ring_fire_g_o.html", null ],
    [ "ModGenesia.RogueGenesiaMod", "class_mod_genesia_1_1_rogue_genesia_mod.html", null ],
    [ "RogueGenesia.Data.RogueZoneVariationContainer", "class_rogue_genesia_1_1_data_1_1_rogue_zone_variation_container.html", null ],
    [ "ScriptableObject", null, [
      [ "RogueGenesia.Data.ChallengeSO", "class_rogue_genesia_1_1_data_1_1_challenge_s_o.html", null ],
      [ "RogueGenesia.Data.CollectibleSO", "class_rogue_genesia_1_1_data_1_1_collectible_s_o.html", null ],
      [ "RogueGenesia.Data.EnemySO", "class_rogue_genesia_1_1_data_1_1_enemy_s_o.html", null ],
      [ "RogueGenesia.Data.EnemySOConversion", "class_rogue_genesia_1_1_data_1_1_enemy_s_o_conversion.html", null ],
      [ "RogueGenesia.Data.GameModeDifficultySO", "class_rogue_genesia_1_1_data_1_1_game_mode_difficulty_s_o.html", [
        [ "RogueGenesia.Data.RogueModeDifficultySO", "class_rogue_genesia_1_1_data_1_1_rogue_mode_difficulty_s_o.html", null ],
        [ "RogueGenesia.Data.SurvivorsModeDifficultySO", "class_rogue_genesia_1_1_data_1_1_survivors_mode_difficulty_s_o.html", null ]
      ] ],
      [ "RogueGenesia.Data.GameModeSO", "class_rogue_genesia_1_1_data_1_1_game_mode_s_o.html", null ],
      [ "RogueGenesia.Data.MonsterTypeCollection", "class_rogue_genesia_1_1_data_1_1_monster_type_collection.html", null ],
      [ "RogueGenesia.Data.RogueGenesiaScriptableObject", "class_rogue_genesia_1_1_data_1_1_rogue_genesia_scriptable_object.html", [
        [ "RogueGenesia.Data.AchievementScriptableObject", "class_rogue_genesia_1_1_data_1_1_achievement_scriptable_object.html", null ],
        [ "RogueGenesia.Data.ArtifactScriptableObject", "class_rogue_genesia_1_1_data_1_1_artifact_scriptable_object.html", null ],
        [ "RogueGenesia.Data.AvatarScriptableObject", "class_rogue_genesia_1_1_data_1_1_avatar_scriptable_object.html", null ],
        [ "RogueGenesia.Data.EnemyPatternScriptableObject", "class_rogue_genesia_1_1_data_1_1_enemy_pattern_scriptable_object.html", null ],
        [ "RogueGenesia.Data.EnemyScriptableObject", "class_rogue_genesia_1_1_data_1_1_enemy_scriptable_object.html", null ],
        [ "RogueGenesia.Data.MonsterTypeScriptableObject", "class_rogue_genesia_1_1_data_1_1_monster_type_scriptable_object.html", null ],
        [ "RogueGenesia.Data.PetScriptableObject", "class_rogue_genesia_1_1_data_1_1_pet_scriptable_object.html", null ],
        [ "RogueGenesia.Data.SoulCardScriptableObject", "class_rogue_genesia_1_1_data_1_1_soul_card_scriptable_object.html", null ],
        [ "RogueGenesia.Data.SoulShopUpgradeSO", "class_rogue_genesia_1_1_data_1_1_soul_shop_upgrade_s_o.html", null ],
        [ "RogueGenesia.Data.TalentScriptableObject", "class_rogue_genesia_1_1_data_1_1_talent_scriptable_object.html", null ]
      ] ],
      [ "RogueGenesia.Data.SCSORequirementList", "class_rogue_genesia_1_1_data_1_1_s_c_s_o_requirement_list.html", null ],
      [ "RogueGenesia.Data.StageObjectiveSO", "class_rogue_genesia_1_1_data_1_1_stage_objective_s_o.html", null ],
      [ "RogueGenesia.Data.StageSO", "class_rogue_genesia_1_1_data_1_1_stage_s_o.html", null ],
      [ "RogueGenesia.Data.SurvivorsModeModuleSO", "class_rogue_genesia_1_1_data_1_1_survivors_mode_module_s_o.html", null ],
      [ "RogueGenesia.RogueZoneSO", "class_rogue_genesia_1_1_rogue_zone_s_o.html", null ]
    ] ],
    [ "RogueGenesia.GameManager.ShopGenerationInfo", "class_rogue_genesia_1_1_game_manager_1_1_shop_generation_info.html", null ],
    [ "RogueGenesia.Data.SingularModifier", "class_rogue_genesia_1_1_data_1_1_singular_modifier.html", null ],
    [ "ModGenesia.SoulCardCreationData", "class_mod_genesia_1_1_soul_card_creation_data.html", null ],
    [ "RogueGenesia.Save.SoulCardSave", "class_rogue_genesia_1_1_save_1_1_soul_card_save.html", null ],
    [ "RogueGenesia.SoulCardUtils", "class_rogue_genesia_1_1_soul_card_utils.html", null ],
    [ "RogueGenesia.Actors.Survival.SoulLevel", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_soul_level.html", [
      [ "RogueGenesia.Actors.Survival.SoulLevelShopKeeper", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_soul_level_shop_keeper.html", null ]
    ] ],
    [ "RogueGenesia.Data.SoulShopUpgradeSave", "class_rogue_genesia_1_1_data_1_1_soul_shop_upgrade_save.html", null ],
    [ "RogueGenesia.GameManager.SSUpgradeTier", "class_rogue_genesia_1_1_game_manager_1_1_s_s_upgrade_tier.html", null ],
    [ "ModGenesia.StageAPI", "class_mod_genesia_1_1_stage_a_p_i.html", null ],
    [ "ModGenesia.StageCreationInfo", "class_mod_genesia_1_1_stage_creation_info.html", null ],
    [ "RogueGenesia.Data.StageInfoClass", "class_rogue_genesia_1_1_data_1_1_stage_info_class.html", [
      [ "RogueGenesia.Data.ArenaInfoClass", "class_rogue_genesia_1_1_data_1_1_arena_info_class.html", null ],
      [ "RogueGenesia.Data.BlackSmithInfoClass", "class_rogue_genesia_1_1_data_1_1_black_smith_info_class.html", null ],
      [ "RogueGenesia.Data.BossInfoClass", "class_rogue_genesia_1_1_data_1_1_boss_info_class.html", null ],
      [ "RogueGenesia.Data.ChestInfoClass", "class_rogue_genesia_1_1_data_1_1_chest_info_class.html", null ],
      [ "RogueGenesia.Data.CombatInfoClass", "class_rogue_genesia_1_1_data_1_1_combat_info_class.html", null ],
      [ "RogueGenesia.Data.EliteInfoClass", "class_rogue_genesia_1_1_data_1_1_elite_info_class.html", null ],
      [ "RogueGenesia.Data.EliteSwarmInfoClass", "class_rogue_genesia_1_1_data_1_1_elite_swarm_info_class.html", null ],
      [ "RogueGenesia.Data.EventInfoClass", "class_rogue_genesia_1_1_data_1_1_event_info_class.html", null ],
      [ "RogueGenesia.Data.MidBossInfoClass", "class_rogue_genesia_1_1_data_1_1_mid_boss_info_class.html", null ],
      [ "RogueGenesia.Data.ShopInfoClass", "class_rogue_genesia_1_1_data_1_1_shop_info_class.html", null ],
      [ "RogueGenesia.Data.SwarmInfoClass", "class_rogue_genesia_1_1_data_1_1_swarm_info_class.html", null ]
    ] ],
    [ "RogueGenesia.Data.StageObjective", "class_rogue_genesia_1_1_data_1_1_stage_objective.html", [
      [ "RogueGenesia.Data.BreakCrate", "class_rogue_genesia_1_1_data_1_1_break_crate.html", null ],
      [ "RogueGenesia.Data.DefendShopKeeper", "class_rogue_genesia_1_1_data_1_1_defend_shop_keeper.html", null ],
      [ "RogueGenesia.Data.EmptyOptional", "class_rogue_genesia_1_1_data_1_1_empty_optional.html", null ],
      [ "RogueGenesia.Data.FangCollection", "class_rogue_genesia_1_1_data_1_1_fang_collection.html", null ],
      [ "RogueGenesia.Data.GoldCollect", "class_rogue_genesia_1_1_data_1_1_gold_collect.html", null ],
      [ "RogueGenesia.Data.KillCount", "class_rogue_genesia_1_1_data_1_1_kill_count.html", [
        [ "RogueGenesia.Data.KillTargetAndKillCount", "class_rogue_genesia_1_1_data_1_1_kill_target_and_kill_count.html", null ]
      ] ],
      [ "RogueGenesia.Data.KillCountAndSurvival", "class_rogue_genesia_1_1_data_1_1_kill_count_and_survival.html", null ],
      [ "RogueGenesia.Data.KillEliteCount", "class_rogue_genesia_1_1_data_1_1_kill_elite_count.html", null ],
      [ "RogueGenesia.Data.KillEliteCountAndSurvival", "class_rogue_genesia_1_1_data_1_1_kill_elite_count_and_survival.html", null ],
      [ "RogueGenesia.Data.KillTarget", "class_rogue_genesia_1_1_data_1_1_kill_target.html", null ],
      [ "RogueGenesia.Data.Survival", "class_rogue_genesia_1_1_data_1_1_survival.html", [
        [ "RogueGenesia.Data.KillTargetAndSurvival", "class_rogue_genesia_1_1_data_1_1_kill_target_and_survival.html", null ]
      ] ],
      [ "RogueGenesia.Data.TimeLimit", "class_rogue_genesia_1_1_data_1_1_time_limit.html", null ],
      [ "RogueGenesia.Data.UntouchedObjective", "class_rogue_genesia_1_1_data_1_1_untouched_objective.html", null ]
    ] ],
    [ "RogueGenesia.Data.StageSO.StageObjectiveWeight", "class_rogue_genesia_1_1_data_1_1_stage_s_o_1_1_stage_objective_weight.html", null ],
    [ "RogueGenesia.Data.StageRewardBonus", "struct_rogue_genesia_1_1_data_1_1_stage_reward_bonus.html", null ],
    [ "RogueGenesia.Data.StageSO.StageWeightModifier", "class_rogue_genesia_1_1_data_1_1_stage_s_o_1_1_stage_weight_modifier.html", null ],
    [ "RogueGenesia.UI.StartGamePannelList", "class_rogue_genesia_1_1_u_i_1_1_start_game_pannel_list.html", null ],
    [ "RogueGenesia.Data.Statistic", "class_rogue_genesia_1_1_data_1_1_statistic.html", null ],
    [ "RogueGenesia.Data.StatModifier", "class_rogue_genesia_1_1_data_1_1_stat_modifier.html", null ],
    [ "RogueGenesia.Data.StatsModifier", "class_rogue_genesia_1_1_data_1_1_stats_modifier.html", null ],
    [ "RogueGenesia.Save.StatsModifierSave", "class_rogue_genesia_1_1_save_1_1_stats_modifier_save.html", null ],
    [ "RogueGenesia.Data.StatsSerializationHelper", "class_rogue_genesia_1_1_data_1_1_stats_serialization_helper.html", null ],
    [ "ModGenesia.SteamWorkShop", "class_mod_genesia_1_1_steam_work_shop.html", null ],
    [ "RogueGenesia.GameManager.SurvivalElite", "class_rogue_genesia_1_1_game_manager_1_1_survival_elite.html", null ],
    [ "RogueGenesia.GameManager.SurvivalModuleTime", "class_rogue_genesia_1_1_game_manager_1_1_survival_module_time.html", null ],
    [ "RogueGenesia.Data.TalentLevelData", "class_rogue_genesia_1_1_data_1_1_talent_level_data.html", null ],
    [ "RogueGenesia.Data.TalentSaveData", "class_rogue_genesia_1_1_data_1_1_talent_save_data.html", null ],
    [ "RogueGenesia.Data.TalentsData", "class_rogue_genesia_1_1_data_1_1_talents_data.html", null ],
    [ "RogueGenesia.Data.TalentsListContainer", "class_rogue_genesia_1_1_data_1_1_talents_list_container.html", null ],
    [ "RogueGenesia.Data.TimeExtension", "class_rogue_genesia_1_1_data_1_1_time_extension.html", null ],
    [ "RogueGenesia.UI.TooltipSection", "class_rogue_genesia_1_1_u_i_1_1_tooltip_section.html", null ],
    [ "RogueGenesia.Actors.Survival.TouchingEntity", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_touching_entity.html", null ],
    [ "UnityEvent", null, [
      [ "RogueGenesia.GameManager.OrderedEvent< T0 >", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event.html", null ],
      [ "RogueGenesia.GameManager.OrderedEvent< T0 >", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event.html", null ],
      [ "RogueGenesia.GameManager.OrderedEvent< T0 >", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event.html", null ],
      [ "RogueGenesia.GameManager.OrderedEvent< T0 >", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event.html", null ]
    ] ],
    [ "RogueGenesia.Data.UnlockData", "struct_rogue_genesia_1_1_data_1_1_unlock_data.html", null ],
    [ "RogueGenesia.Save.Vector3Save", "struct_rogue_genesia_1_1_save_1_1_vector3_save.html", null ],
    [ "RogueGenesia.Actors.Survival.Weapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_weapon.html", [
      [ "RogueGenesia.Actors.Survival.ArcanistStaff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_arcanist_staff.html", null ],
      [ "RogueGenesia.Actors.Survival.BowWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_bow_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.CleaveWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_cleave_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.CrossBowWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_cross_bow_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.CursedBoltWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_cursed_bolt_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.DeathScytheWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_death_scythe_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.EvilRing", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_evil_ring.html", null ],
      [ "RogueGenesia.Actors.Survival.ExplosiveVial", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_explosive_vial.html", null ],
      [ "RogueGenesia.Actors.Survival.FireAura", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_fire_aura.html", null ],
      [ "RogueGenesia.Actors.Survival.FireKatanaWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_fire_katana_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.FireRingWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_fire_ring_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.FuumaShurikenWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_fuuma_shuriken_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.GunSlingerWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_gun_slinger_weapon.html", [
        [ "RogueGenesia.Actors.Survival.AutoShotgunWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_auto_shotgun_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.BoltActionWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_bolt_action_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.MachineGunWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_machine_gun_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.PistolWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_pistol_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.RevolverWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_revolver_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.RifleWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_rifle_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.SMGWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_s_m_g_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.ScatterGunWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_scatter_gun_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.ShotgunWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_shotgun_weapon.html", null ],
        [ "RogueGenesia.Actors.Survival.SniperWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_sniper_weapon.html", null ]
      ] ],
      [ "RogueGenesia.Actors.Survival.KatanaWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_katana_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.KunaiWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_kunai_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.MagicWandWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_magic_wand_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.MagicWispWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_magic_wisp_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.PikeWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_pike_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.ShamanStaff", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_shaman_staff.html", null ],
      [ "RogueGenesia.Actors.Survival.ShurikenWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_shuriken_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.SpearWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_spear_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.StormStaffWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_storm_staff_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.SwordrangWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_swordrang_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.ThrowingKnifeWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_throwing_knife_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.ThunderStaffWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_thunder_staff_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.ThunderVialWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_thunder_vial_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.VoidWispWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_void_wisp_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.WindBladeWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_wind_blade_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.WindKatanaWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_wind_katana_weapon.html", null ],
      [ "RogueGenesia.Actors.Survival.WormGlandWeapon", "class_rogue_genesia_1_1_actors_1_1_survival_1_1_worm_gland_weapon.html", null ],
      [ "RogueGenesia.Data.InterdimensionalRoseWeapon", "class_rogue_genesia_1_1_data_1_1_interdimensional_rose_weapon.html", null ],
      [ "RogueGenesia.Data.ThornSoulCard", "class_rogue_genesia_1_1_data_1_1_thorn_soul_card.html", null ]
    ] ],
    [ "RogueGenesia.WeightedPicker< T >.WeightClass", "class_rogue_genesia_1_1_weighted_picker_1_1_weight_class.html", null ],
    [ "RogueGenesia.WeightedPicker< T >", "class_rogue_genesia_1_1_weighted_picker.html", null ],
    [ "RogueGenesia.WeightedPicker< RogueGenesia.Data.EnemySO >", "class_rogue_genesia_1_1_weighted_picker.html", null ],
    [ "RogueGenesia.WeightedPicker< RogueGenesia.Data.StageObjectiveSO >", "class_rogue_genesia_1_1_weighted_picker.html", null ],
    [ "RogueGenesia.Data.MagicWispTalent.wispProj", "class_rogue_genesia_1_1_data_1_1_magic_wisp_talent_1_1wisp_proj.html", null ],
    [ "ModGenesia.SteamWorkShop.WorkshopDownloadProgress", "class_mod_genesia_1_1_steam_work_shop_1_1_workshop_download_progress.html", null ],
    [ "ModGenesia.WorkShopInformation", "class_mod_genesia_1_1_work_shop_information.html", null ],
    [ "RogueGenesia.Data.ZoneMusic", "class_rogue_genesia_1_1_data_1_1_zone_music.html", null ]
];