var namespace_rogue_genesia_1_1_game_manager =
[
    [ "Menu", "namespace_rogue_genesia_1_1_game_manager_1_1_menu.html", "namespace_rogue_genesia_1_1_game_manager_1_1_menu" ],
    [ "CollectibleManager", "class_rogue_genesia_1_1_game_manager_1_1_collectible_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_collectible_manager" ],
    [ "DynamicDifficultyManager", "class_rogue_genesia_1_1_game_manager_1_1_dynamic_difficulty_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_dynamic_difficulty_manager" ],
    [ "DynamicDifficultyManagerRogue", "class_rogue_genesia_1_1_game_manager_1_1_dynamic_difficulty_manager_rogue.html", "class_rogue_genesia_1_1_game_manager_1_1_dynamic_difficulty_manager_rogue" ],
    [ "MonsterSpawnQueue", "class_rogue_genesia_1_1_game_manager_1_1_monster_spawn_queue.html", "class_rogue_genesia_1_1_game_manager_1_1_monster_spawn_queue" ],
    [ "EnemyManager", "class_rogue_genesia_1_1_game_manager_1_1_enemy_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_enemy_manager" ],
    [ "HealthBarBuffer", "struct_rogue_genesia_1_1_game_manager_1_1_health_bar_buffer.html", "struct_rogue_genesia_1_1_game_manager_1_1_health_bar_buffer" ],
    [ "DamageNumberData", "struct_rogue_genesia_1_1_game_manager_1_1_damage_number_data.html", "struct_rogue_genesia_1_1_game_manager_1_1_damage_number_data" ],
    [ "ThunderFXData", "struct_rogue_genesia_1_1_game_manager_1_1_thunder_f_x_data.html", "struct_rogue_genesia_1_1_game_manager_1_1_thunder_f_x_data" ],
    [ "RiftFXData", "struct_rogue_genesia_1_1_game_manager_1_1_rift_f_x_data.html", "struct_rogue_genesia_1_1_game_manager_1_1_rift_f_x_data" ],
    [ "GunTraceData", "struct_rogue_genesia_1_1_game_manager_1_1_gun_trace_data.html", "struct_rogue_genesia_1_1_game_manager_1_1_gun_trace_data" ],
    [ "ThunderStrikeFXData", "struct_rogue_genesia_1_1_game_manager_1_1_thunder_strike_f_x_data.html", "struct_rogue_genesia_1_1_game_manager_1_1_thunder_strike_f_x_data" ],
    [ "ShockWaveFXData", "struct_rogue_genesia_1_1_game_manager_1_1_shock_wave_f_x_data.html", "struct_rogue_genesia_1_1_game_manager_1_1_shock_wave_f_x_data" ],
    [ "FXManager", "class_rogue_genesia_1_1_game_manager_1_1_f_x_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_f_x_manager" ],
    [ "GameManagerCorridor", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_corridor.html", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_corridor" ],
    [ "GameManagerFight", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_fight.html", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_fight" ],
    [ "GameManagerRogue", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_rogue.html", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_rogue" ],
    [ "SurvivalElite", "class_rogue_genesia_1_1_game_manager_1_1_survival_elite.html", "class_rogue_genesia_1_1_game_manager_1_1_survival_elite" ],
    [ "SurvivalModuleTime", "class_rogue_genesia_1_1_game_manager_1_1_survival_module_time.html", "class_rogue_genesia_1_1_game_manager_1_1_survival_module_time" ],
    [ "GameManagerSurvival", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_survival.html", "class_rogue_genesia_1_1_game_manager_1_1_game_manager_survival" ],
    [ "GamePlayManager", "class_rogue_genesia_1_1_game_manager_1_1_game_play_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_game_play_manager" ],
    [ "ProceduralObjectPlacement", "class_rogue_genesia_1_1_game_manager_1_1_procedural_object_placement.html", "class_rogue_genesia_1_1_game_manager_1_1_procedural_object_placement" ],
    [ "ProjectileManager", "class_rogue_genesia_1_1_game_manager_1_1_projectile_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_projectile_manager" ],
    [ "SummonManager", "class_rogue_genesia_1_1_game_manager_1_1_summon_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_summon_manager" ],
    [ "ZoneSelectionManager", "class_rogue_genesia_1_1_game_manager_1_1_zone_selection_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_zone_selection_manager" ],
    [ "DiscordManager", "class_rogue_genesia_1_1_game_manager_1_1_discord_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_discord_manager" ],
    [ "CardWeightEventInfo", "class_rogue_genesia_1_1_game_manager_1_1_card_weight_event_info.html", "class_rogue_genesia_1_1_game_manager_1_1_card_weight_event_info" ],
    [ "DeathStatue", "class_rogue_genesia_1_1_game_manager_1_1_death_statue.html", "class_rogue_genesia_1_1_game_manager_1_1_death_statue" ],
    [ "BoolValue", "class_rogue_genesia_1_1_game_manager_1_1_bool_value.html", "class_rogue_genesia_1_1_game_manager_1_1_bool_value" ],
    [ "FloatValue", "class_rogue_genesia_1_1_game_manager_1_1_float_value.html", "class_rogue_genesia_1_1_game_manager_1_1_float_value" ],
    [ "IntValue", "class_rogue_genesia_1_1_game_manager_1_1_int_value.html", "class_rogue_genesia_1_1_game_manager_1_1_int_value" ],
    [ "StringValue", "class_rogue_genesia_1_1_game_manager_1_1_string_value.html", "class_rogue_genesia_1_1_game_manager_1_1_string_value" ],
    [ "OrderedEvent&lt; T0, T1, T2, T3 &gt;", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-4-g.html", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-4-g" ],
    [ "OrderedEvent&lt; T0, T1, T2 &gt;", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-3-g.html", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-3-g" ],
    [ "OrderedEvent&lt; T0, T1 &gt;", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-2-g.html", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-2-g" ],
    [ "OrderedEvent&lt; T0 &gt;", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-1-g.html", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event-1-g" ],
    [ "OrderedEvent", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event.html", "class_rogue_genesia_1_1_game_manager_1_1_ordered_event" ],
    [ "GameEventManager", "class_rogue_genesia_1_1_game_manager_1_1_game_event_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_game_event_manager" ],
    [ "MouseCursorManager", "class_rogue_genesia_1_1_game_manager_1_1_mouse_cursor_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_mouse_cursor_manager" ],
    [ "RecentSoundContainer", "class_rogue_genesia_1_1_game_manager_1_1_recent_sound_container.html", "class_rogue_genesia_1_1_game_manager_1_1_recent_sound_container" ],
    [ "SoundManager", "class_rogue_genesia_1_1_game_manager_1_1_sound_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_sound_manager" ],
    [ "RecapData", "class_rogue_genesia_1_1_game_manager_1_1_recap_data.html", "class_rogue_genesia_1_1_game_manager_1_1_recap_data" ],
    [ "DamageSourceInfo", "struct_rogue_genesia_1_1_game_manager_1_1_damage_source_info.html", "struct_rogue_genesia_1_1_game_manager_1_1_damage_source_info" ],
    [ "GameEndManager", "class_rogue_genesia_1_1_game_manager_1_1_game_end_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_game_end_manager" ],
    [ "RewardManager", "class_rogue_genesia_1_1_game_manager_1_1_reward_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_reward_manager" ],
    [ "SSUpgradeTier", "class_rogue_genesia_1_1_game_manager_1_1_s_s_upgrade_tier.html", "class_rogue_genesia_1_1_game_manager_1_1_s_s_upgrade_tier" ],
    [ "SoulShopManager", "class_rogue_genesia_1_1_game_manager_1_1_soul_shop_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_soul_shop_manager" ],
    [ "BlackMarket", "class_rogue_genesia_1_1_game_manager_1_1_black_market.html", "class_rogue_genesia_1_1_game_manager_1_1_black_market" ],
    [ "NormalShop", "class_rogue_genesia_1_1_game_manager_1_1_normal_shop.html", "class_rogue_genesia_1_1_game_manager_1_1_normal_shop" ],
    [ "ShopKeeperShopManager", "class_rogue_genesia_1_1_game_manager_1_1_shop_keeper_shop_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_shop_keeper_shop_manager" ],
    [ "ShopLockInfo", "struct_rogue_genesia_1_1_game_manager_1_1_shop_lock_info.html", "struct_rogue_genesia_1_1_game_manager_1_1_shop_lock_info" ],
    [ "SpecialManager", "class_rogue_genesia_1_1_game_manager_1_1_special_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_special_manager" ],
    [ "ShopGenerationInfo", "class_rogue_genesia_1_1_game_manager_1_1_shop_generation_info.html", "class_rogue_genesia_1_1_game_manager_1_1_shop_generation_info" ],
    [ "ShopManager", "class_rogue_genesia_1_1_game_manager_1_1_shop_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_shop_manager" ],
    [ "DetailCardInfoHistory", "class_rogue_genesia_1_1_game_manager_1_1_detail_card_info_history.html", "class_rogue_genesia_1_1_game_manager_1_1_detail_card_info_history" ],
    [ "DetailedCardInformationManager", "class_rogue_genesia_1_1_game_manager_1_1_detailed_card_information_manager.html", "class_rogue_genesia_1_1_game_manager_1_1_detailed_card_information_manager" ],
    [ "EEndGameState", "namespace_rogue_genesia_1_1_game_manager.html#a1c5c58caee0193317a25c371dd5e0ae6", [
      [ "GameOver", "namespace_rogue_genesia_1_1_game_manager.html#a1c5c58caee0193317a25c371dd5e0ae6a8f347bc7cebca9fa6d97e70c6bc29eb3", null ],
      [ "Victory", "namespace_rogue_genesia_1_1_game_manager.html#a1c5c58caee0193317a25c371dd5e0ae6a1f5c647d9066bc9e350b70aa2d16aec4", null ],
      [ "Infinity", "namespace_rogue_genesia_1_1_game_manager.html#a1c5c58caee0193317a25c371dd5e0ae6aeb2ac5b04180d8d6011a016aeb8f75b3", null ]
    ] ]
];