var namespace_rogue_genesia =
[
    [ "Actors", "namespace_rogue_genesia_1_1_actors.html", "namespace_rogue_genesia_1_1_actors" ],
    [ "Data", "namespace_rogue_genesia_1_1_data.html", "namespace_rogue_genesia_1_1_data" ],
    [ "UI", "namespace_rogue_genesia_1_1_u_i.html", "namespace_rogue_genesia_1_1_u_i" ],
    [ "GameManager", "namespace_rogue_genesia_1_1_game_manager.html", "namespace_rogue_genesia_1_1_game_manager" ],
    [ "Save", "namespace_rogue_genesia_1_1_save.html", "namespace_rogue_genesia_1_1_save" ],
    [ "Environement", "namespace_rogue_genesia_1_1_environement.html", "namespace_rogue_genesia_1_1_environement" ],
    [ "Pooling", "namespace_rogue_genesia_1_1_pooling.html", "namespace_rogue_genesia_1_1_pooling" ],
    [ "Utils", "namespace_rogue_genesia_1_1_utils.html", "namespace_rogue_genesia_1_1_utils" ],
    [ "AchievementSave", "struct_rogue_genesia_1_1_achievement_save.html", "struct_rogue_genesia_1_1_achievement_save" ],
    [ "AchievementSaveData", "class_rogue_genesia_1_1_achievement_save_data.html", "class_rogue_genesia_1_1_achievement_save_data" ],
    [ "AchievementManager", "class_rogue_genesia_1_1_achievement_manager.html", "class_rogue_genesia_1_1_achievement_manager" ],
    [ "OnboardingManager", "class_rogue_genesia_1_1_onboarding_manager.html", "class_rogue_genesia_1_1_onboarding_manager" ],
    [ "AdvancedColorSettings", "class_rogue_genesia_1_1_advanced_color_settings.html", "class_rogue_genesia_1_1_advanced_color_settings" ],
    [ "AdvancedStageColorSettings", "class_rogue_genesia_1_1_advanced_stage_color_settings.html", "class_rogue_genesia_1_1_advanced_stage_color_settings" ],
    [ "AdvancedLightingSettings", "class_rogue_genesia_1_1_advanced_lighting_settings.html", "class_rogue_genesia_1_1_advanced_lighting_settings" ],
    [ "BakedFogSettings", "class_rogue_genesia_1_1_baked_fog_settings.html", "class_rogue_genesia_1_1_baked_fog_settings" ],
    [ "ColorSet", "class_rogue_genesia_1_1_color_set.html", "class_rogue_genesia_1_1_color_set" ],
    [ "ColorDecal", "class_rogue_genesia_1_1_color_decal.html", "class_rogue_genesia_1_1_color_decal" ],
    [ "GameColorDataHolder", "class_rogue_genesia_1_1_game_color_data_holder.html", "class_rogue_genesia_1_1_game_color_data_holder" ],
    [ "ColorManagement", "class_rogue_genesia_1_1_color_management.html", "class_rogue_genesia_1_1_color_management" ],
    [ "ColorSchemeSO", "class_rogue_genesia_1_1_color_scheme_s_o.html", "class_rogue_genesia_1_1_color_scheme_s_o" ],
    [ "StageColorManager", "class_rogue_genesia_1_1_stage_color_manager.html", "class_rogue_genesia_1_1_stage_color_manager" ],
    [ "EnvironementSpawnType", "class_rogue_genesia_1_1_environement_spawn_type.html", null ],
    [ "RogueZoneSO", "class_rogue_genesia_1_1_rogue_zone_s_o.html", "class_rogue_genesia_1_1_rogue_zone_s_o" ],
    [ "Index", "class_rogue_genesia_1_1_index.html", "class_rogue_genesia_1_1_index" ],
    [ "String", "class_rogue_genesia_1_1_string.html", "class_rogue_genesia_1_1_string" ],
    [ "Proxy", "struct_rogue_genesia_1_1_proxy.html", "struct_rogue_genesia_1_1_proxy" ],
    [ "InfinityColorData", "class_rogue_genesia_1_1_infinity_color_data.html", "class_rogue_genesia_1_1_infinity_color_data" ],
    [ "EquipmentFXUtils", "class_rogue_genesia_1_1_equipment_f_x_utils.html", "class_rogue_genesia_1_1_equipment_f_x_utils" ],
    [ "GetChallengeProgression", "class_rogue_genesia_1_1_get_challenge_progression.html", "class_rogue_genesia_1_1_get_challenge_progression" ],
    [ "GetEquipmentQuality", "class_rogue_genesia_1_1_get_equipment_quality.html", "class_rogue_genesia_1_1_get_equipment_quality" ],
    [ "MathUtils", "class_rogue_genesia_1_1_math_utils.html", "class_rogue_genesia_1_1_math_utils" ],
    [ "SumProd", "struct_rogue_genesia_1_1_sum_prod.html", "struct_rogue_genesia_1_1_sum_prod" ],
    [ "ΣΠ", "struct_rogue_genesia_1_1_xCE_xA3_xCE_xA0.html", "struct_rogue_genesia_1_1_xCE_xA3_xCE_xA0" ],
    [ "Ŧ", "struct_rogue_genesia_1_1_xC5_xA6.html", "struct_rogue_genesia_1_1_xC5_xA6" ],
    [ "GetSoulCoinGain", "class_rogue_genesia_1_1_get_soul_coin_gain.html", "class_rogue_genesia_1_1_get_soul_coin_gain" ],
    [ "Get", "class_rogue_genesia_1_1_get.html", "class_rogue_genesia_1_1_get" ],
    [ "DebugLog", "struct_rogue_genesia_1_1_debug_log.html", "struct_rogue_genesia_1_1_debug_log" ],
    [ "ToDebug", "struct_rogue_genesia_1_1_to_debug.html", "struct_rogue_genesia_1_1_to_debug" ],
    [ "RGMath", "class_rogue_genesia_1_1_r_g_math.html", "class_rogue_genesia_1_1_r_g_math" ],
    [ "RGDebug", "class_rogue_genesia_1_1_r_g_debug.html", "class_rogue_genesia_1_1_r_g_debug" ],
    [ "EditorRGUtils", "class_rogue_genesia_1_1_editor_r_g_utils.html", "class_rogue_genesia_1_1_editor_r_g_utils" ],
    [ "DifficultyWeightedPicker&lt; T &gt;", "class_rogue_genesia_1_1_difficulty_weighted_picker-1-g.html", "class_rogue_genesia_1_1_difficulty_weighted_picker-1-g" ],
    [ "WeightedPicker&lt; T &gt;", "class_rogue_genesia_1_1_weighted_picker-1-g.html", "class_rogue_genesia_1_1_weighted_picker-1-g" ],
    [ "RGRichText", "class_rogue_genesia_1_1_r_g_rich_text.html", "class_rogue_genesia_1_1_r_g_rich_text" ],
    [ "RGUtils", "class_rogue_genesia_1_1_r_g_utils.html", "class_rogue_genesia_1_1_r_g_utils" ],
    [ "SoulCardUtils", "class_rogue_genesia_1_1_soul_card_utils.html", "class_rogue_genesia_1_1_soul_card_utils" ],
    [ "UI_FXCanvas", "class_rogue_genesia_1_1_u_i___f_x_canvas.html", "class_rogue_genesia_1_1_u_i___f_x_canvas" ],
    [ "AchievementNotification", "class_rogue_genesia_1_1_achievement_notification.html", "class_rogue_genesia_1_1_achievement_notification" ],
    [ "CustomGameChallengeUI", "class_rogue_genesia_1_1_custom_game_challenge_u_i.html", "class_rogue_genesia_1_1_custom_game_challenge_u_i" ],
    [ "CustomGameStatModifier", "class_rogue_genesia_1_1_custom_game_stat_modifier.html", "class_rogue_genesia_1_1_custom_game_stat_modifier" ],
    [ "CustomGameUIManager", "class_rogue_genesia_1_1_custom_game_u_i_manager.html", "class_rogue_genesia_1_1_custom_game_u_i_manager" ],
    [ "InputImage", "class_rogue_genesia_1_1_input_image.html", "class_rogue_genesia_1_1_input_image" ],
    [ "KeyWordPromptSlot", "class_rogue_genesia_1_1_key_word_prompt_slot.html", "class_rogue_genesia_1_1_key_word_prompt_slot" ],
    [ "EquipmentTooltip", "class_rogue_genesia_1_1_equipment_tooltip.html", "class_rogue_genesia_1_1_equipment_tooltip" ],
    [ "ModifierCraftingMenu", "class_rogue_genesia_1_1_modifier_crafting_menu.html", "class_rogue_genesia_1_1_modifier_crafting_menu" ],
    [ "ModifierCraftingUI", "class_rogue_genesia_1_1_modifier_crafting_u_i.html", "class_rogue_genesia_1_1_modifier_crafting_u_i" ],
    [ "SoulShopUpgradePanel", "class_rogue_genesia_1_1_soul_shop_upgrade_panel.html", "class_rogue_genesia_1_1_soul_shop_upgrade_panel" ],
    [ "EmptyModifier_Forge", "class_rogue_genesia_1_1_empty_modifier___forge.html", "class_rogue_genesia_1_1_empty_modifier___forge" ],
    [ "Equipment_Tooltip_Modifier", "class_rogue_genesia_1_1_equipment___tooltip___modifier.html", "class_rogue_genesia_1_1_equipment___tooltip___modifier" ],
    [ "EquipmentModifier_CreationUI", "class_rogue_genesia_1_1_equipment_modifier___creation_u_i.html", "class_rogue_genesia_1_1_equipment_modifier___creation_u_i" ],
    [ "EquipmentModifier_EncyclopediaUI", "class_rogue_genesia_1_1_equipment_modifier___encyclopedia_u_i.html", "class_rogue_genesia_1_1_equipment_modifier___encyclopedia_u_i" ],
    [ "EquipmentModifierList", "class_rogue_genesia_1_1_equipment_modifier_list.html", "class_rogue_genesia_1_1_equipment_modifier_list" ],
    [ "MainModifier_Forge", "class_rogue_genesia_1_1_main_modifier___forge.html", "class_rogue_genesia_1_1_main_modifier___forge" ],
    [ "ModifierCrafting", "class_rogue_genesia_1_1_modifier_crafting.html", "class_rogue_genesia_1_1_modifier_crafting" ],
    [ "SecondaryModifier_Forge", "class_rogue_genesia_1_1_secondary_modifier___forge.html", "class_rogue_genesia_1_1_secondary_modifier___forge" ],
    [ "EStatDisplayMode", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95c", [
      [ "Default", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95ca7a1920d61156abc05a60135aefe8bc67", null ],
      [ "Split", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95ca8a9e64d86ed12ad40de129bc7f4683b2", null ],
      [ "Percent", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95caadaaee4b22041c27198d410c68d952c9", null ],
      [ "PercentFlat", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95ca6e18ea550a1b9bf25e5d5b3fa19f3048", null ],
      [ "InvertedPercent", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95ca4f99319cffcebcd8a1a50adbb7ba2732", null ],
      [ "DamageMitigation", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95ca1fa31a1bad4b4318e2cabd41614f4f09", null ],
      [ "Hide", "namespace_rogue_genesia.html#a08e147a553a0e3cd2fd9a832fe37f95ca62a5e490880a92eef74f167d9dc6dca0", null ]
    ] ],
    [ "EStatLinkDisplay", "namespace_rogue_genesia.html#af3d65b53316b291f97523f9402bcff7f", [
      [ "Base", "namespace_rogue_genesia.html#af3d65b53316b291f97523f9402bcff7fa095a1b43effec73955e31e790438de49", null ],
      [ "Multiplier", "namespace_rogue_genesia.html#af3d65b53316b291f97523f9402bcff7faee34a21131a5636ee8dcf521e2369bee", null ],
      [ "Final", "namespace_rogue_genesia.html#af3d65b53316b291f97523f9402bcff7fabeae421a14a34f831c113f61323d1ab3", null ],
      [ "Default", "namespace_rogue_genesia.html#af3d65b53316b291f97523f9402bcff7fa7a1920d61156abc05a60135aefe8bc67", null ]
    ] ]
];